### ISSUE TITLE
Flatpak'd app doesn't have option to "use native notifications"

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.telegram.desktop#1]
What happened:
1) Install org.telegram.desktop from flathub
2) Open the app and sign in
3) Use the hamburger icon to open the sidebar and select settings
4) Notice how there is no "use native notifications" option under Notifications

What I expected to happen:
At step #4 for there to be an option for native notifications, much like the app directly from the website [0]. Note that I have seen notifications from HexChat and Corebird when both are packaged as flatpaks (however they are both based off the gnome runtime, so maybe there is a package missing).

Below is an image comparing flatpak on the left and the app from the website on the right
![screenshot from 2017-10-06 20-38-45](https://user-images.githubusercontent.com/3669750/31295443-88cf12f8-aad6-11e7-9b4c-c4e1997f14c8.png)

0 - https://desktop.telegram.org/

```
$ flatpak --version
Flatpak 0.9.98.1
$ flatpak info org.telegram.desktop 
Ref: app/org.telegram.desktop/x86_64/stable
ID: org.telegram.desktop
Arch: x86_64
Branch: stable
Origin: flathub
Commit: 9fa70052e83dc8648ccd581ef543d8a390f748b971bf2840ad280075c7e29591
Location: /var/lib/flatpak/app/org.telegram.desktop/x86_64/stable/9fa70052e83dc8648ccd581ef543d8a390f748b971bf2840ad280075c7e29591
Installed size: 40.2 MB
Runtime: org.kde.Platform/x86_64/5.9
```

**Comment by TingPing** [comment]
Does: `flatpak run --talk-name=org.freedesktop.Notifications org.telegram.desktop` change anything?

**Comment by TingPing** [comment]
Also the "native notification" thing is probably specific to the website but notifications themselves should work with that.

**Comment by ahayzen** [comment]
@TingPing Using `--talk-name=org.freedesktop.Notifications` didn't change anything :-/ I think it can't find libnotify.

Note that I was not talking about Telegram web as the working case, I was talking about using Telegram desktop but the appimage (?) version available from their website. Again below is a screenshot showing that on the left with flatpak doesn't work, whereas appimage (?) it does (but not cropped as tightly to show it's not a website).

![screenshot from 2017-10-07 07-21-09](https://user-images.githubusercontent.com/3669750/31305426-5d05c166-ab31-11e7-897d-fdff8dcf942b.png)

I have also found some logs which maybe useful

In the appimage (?) version I can see the line
`[2017.10.06 11:35:57] LibNotify capabilities: actions, body, body-markup, icon-static, persistence, sound`

Whereas in the flatpak version I can see
```
[2017.10.07 07:27:15] Could not load 'notify' with version 4 :(
[2017.10.07 07:27:15] Could not load 'notify' with version 5 :(
[2017.10.07 07:27:15] Could not load 'notify' with version 1 :(
```

I can supply more logs if required.

Furthermore I have found the issue [1] that requested the feature in telegram desktop, here (towards the end) they discuss things like libnotifiy, quirks in different envs and at the very end someone else also states the flatpak version is not working correctly.

1 - https://github.com/telegramdesktop/tdesktop/issues/91

**Comment by AsavarTzeth** [comment]
"Native Notifications" is optional libnotify support that the user has to enable in the Telegram app. As you can see in the mentioned issue thread, it was added because a lot of users did not like the fact that Telegram used its own notifications.

For this to work libnotify needs to be available, otherwise Telegram will hide the option.

**Comment by ahayzen** [comment]
I can confirm after the latest update that native notifications now work correctly, thanks everyone :-)
