### ISSUE TITLE
-workdir flag is ignored

### ISSUE THREAD

**Issue by jamick** [flathub/org.telegram.desktop#100]
The `-workdir` flag seems to be ignored when used in conjunction with `-many`

Previously this command worked: `flatpak run org.telegram.desktop -many -workdir /home/jack/.var/app/org.telegram.desktop/data/TelegramSecondary`

**Comment by grulja** [comment]
I think this would be best to report to Telegram upstream.

**Comment by jamick** [comment]
Hi @grulja, 

I've reported this to the tdesktop dev. I did some testing and the -workdir flag works as expected in the latest version from https://desktop.telegram.org . The flatpak version doesn't accept this flag but previously did so it seems that there is an issue with the flatpak build. Can this issue be re-opened and investigated?
