### ISSUE TITLE
Telegram with the Qt platform theme "gnome" provided by QGnomePlatform uses a wrong font, while the GTK file picker is broken on Wayland

### ISSUE THREAD

**Issue by Bryophyllum** [flathub/org.telegram.desktop#102]
`QT_QPA_PLATFORMTHEME='gnome'`:
![telegram_wayland_qgnomeplatform](https://user-images.githubusercontent.com/27376783/66771382-6528a100-eeba-11e9-984f-c82cb99aa1cb.png)

Qt's default platform theme:
![telegram_wayland_qt_platformtheme](https://user-images.githubusercontent.com/27376783/66771388-69ed5500-eeba-11e9-86f4-c59e9557d080.png)

**Comment by grulja** [comment]
You are not supposed to be overriding the platform theme, with that you avoid using portals and won't be able to properly open/save files.
