### ISSUE TITLE
Native notifications on by default

### ISSUE THREAD

**Issue by jimmac** [flathub/org.telegram.desktop#103]
Having native notification on by default seems sensible. I assume the downside of it enabled is environments with no notifications in place not having notifications. Which sounds like the userbase ready to enable a workaround in the preferences, rather than everyone else.

**Comment by TingPing** [comment]
Sounds like an issue for upstream: https://github.com/telegramdesktop/tdesktop

Also its easy to know if notifications aren't supported and fallback.

**Comment by jimmac** [comment]
Looks like it has been filed upstream 2 years ago -- https://github.com/telegramdesktop/tdesktop/issues/3831

**Comment by gasinvein** [comment]
We don't want to patch anything that's not specific to flatpak, sorry. If you believe Telegram should behave differently in some way - ask upstream to change it.
