### ISSUE TITLE
Copypaste from Telegram on XWayland doesn't work

### ISSUE THREAD

**Issue by Latesil** [flathub/org.telegram.desktop#104]
Copypaste from Telegram doesn't work when I use XWayland. If I run program with` flatpak run --command=Telegram --env=QT_QPA_PLATFORM=wayland org.telegram.desktop` it works. Copypaste on XWayland doesn't work only from Telegram to any other programs. It works within Telegram, or from another program to Telegram. 

Fedora 31, GNOME 3.34.1, Wayland Session
```Telegram Desktop - Telegram Desktop messenger

          ID: org.telegram.desktop
         Ref: app/org.telegram.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.8.14
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 112.6 MB
     Runtime: org.kde.Platform/x86_64/5.13
         Sdk: org.kde.Sdk/x86_64/5.13

      Commit: 423e55278d4ba4ac21d9df7878f0570c067e30310e6119a912d80077b094fc52
      Parent: 73f8b10b8cd37db81d082f48e37d8b3a27e8b04a812156916b5a18ea35de45f5
     Subject: Update to 1.8.14 (296433b0)
        Date: 2019-10-07 14:06:19 +0000```

**Comment by grulja** [comment]
I think you are hitting this issue in Gnome: https://bugzilla.redhat.com/show_bug.cgi?id=1758873.
