### ISSUE TITLE
Telegram won't launch with bwrap error

### ISSUE THREAD

**Issue by lakerssuperman** [flathub/org.telegram.desktop#108]
Running Fedora 31.  Just updated everything.  Restarted my computer.  When I tried to run Telegram it didn't launch so I ran it from the terminal and got:

"bwrap: Can't create file at /run/user/1000/pulse/native: No such device or address"

I have uninstalled the Telegram Flatpak, deleted the Telegram folder in var in my home directory.  Reinstalled and I am still getting the error.

Yesterday I did a Flatpak override on the filesystem to access files outside the sandbox, but then I reverted it.  Could that be causing this issue?

**Comment by grulja** [comment]
Is this happening only with Telegram or also with any other flatpak?

**Comment by lakerssuperman** [comment]
Only Telegram isn't working.  Lollypop and Geary Flatpaks still work just fine on my system.

**Comment by grulja** [comment]
I don't have any problem with Telegram and most likely nobody else, otherwise I would definitely got some other bug reports. It looks you somehow messed with your installation.

You can try to run "flatpak repair".

**Comment by lakerssuperman** [comment]
I'm at a loss.  I ran flatpak repair and it found orphaned files, but Telegram still doesn't run.  I would not be opposed to completely wiping the Telegram Flatpak and all of its config info off the system, but I'm not sure how to do that since I thought I did it already and it clearly didn't work.
