### ISSUE TITLE
Choose file dialog opens in background

### ISSUE THREAD

**Issue by Esokrates** [flathub/org.telegram.desktop#110]
This happens to me in gnome-shell: When attaching a file, the file chooser appears behind the telegram window (is not focused) and I get a notification that the file chooser portal is ready.
This is really annoying behavior, don't know if this is directly related to telegram, but I do not observe the issue with other apps.

**Comment by grulja** [comment]
Duplicate of https://github.com/flathub/org.telegram.desktop/issues/110.
