### ISSUE TITLE
Triple accents input

### ISSUE THREAD

**Issue by Yajo** [flathub/org.telegram.desktop#113]
I don't know what's happening, but since today when I write an accent such as á, in Telegram it apears as ááá:

![Peek 13-11-2019 11-06](https://user-images.githubusercontent.com/973709/68758427-b769f880-0605-11ea-91c1-a485480238ef.gif)

**Comment by hfluz** [comment]
The same is happening with me, but the character is repeated 5 times instead.

**Comment by Yajo** [comment]
Weird, it works fine now...

**Comment by gasinvein** [comment]
@Yajo Telegram had several releases since then. Maybe it was an upstream issue now fixed.

Feel free to reopen if the issue persists or re-appears for you.
