### ISSUE TITLE
No tray icon after latest update

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.telegram.desktop#131]
It seems that Telegram does not show any tray icon anymore after the latest (1.9.7) update. It worked fine before.

Fedora 31
gnome-shell-extension-topicons-plus-22-6.fc31.20191031.0a35713.noarch

**Comment by grulja** [comment]
I believe this is because Telegram now doesn't use libappindicator and uses QSystemTray icon instead which doesn't work in Flatpak very well, because there is no DBus access to StatusNotifier* interfaces.

**Comment by Erick555** [comment]
Would something like `--own-name=org.kde.StatusNotifierItem-<x>-<x>` help?

**Comment by grulja** [comment]
It should, but I'm not sure it will work on 100%, problem is that the last <x> is PID number, which cannot be determined in advance.

**Comment by AsciiWolf** [comment]
There was a KDE Runtime update today and Telegram tray icon started showing again after the update. :-) Not sure what changed, but the issue is now fixed!

**Comment by AsciiWolf** [comment]
And it's gone again after the latest KDE runtime update. :(

**Comment by Erick555** [comment]
Could it be recent accidental build with qt 5.14? You may open test PR which uses 5.14 branch to check that.

**Comment by AsciiWolf** [comment]
Now, after today's ("Update runtime to 5.14") update, it is even worse! Tray icon still seems to be missing, however running Telegram from GNOME Shell Overview now launches a new Flatpak instance every time. So basically an user with end with multiple Telegram instances running at the same time. The duplicate ones eventually get killed, but they can still cause issues. Telegram behaves incorrectly when running multiple times.

**Comment by AsciiWolf** [comment]
It looks like the issue was fixed by #142 and tray icon now appears. :-)
