### ISSUE TITLE
Telegram version is outdated on the website

### ISSUE THREAD

**Issue by gasinvein** [flathub/org.telegram.desktop#137]
[flathub.org page](https://flathub.org/apps/details/org.telegram.desktop) shows Telegram version 1.8.15, while the app is actually 1.9.9 and have been updated several times before (at least there was 1.9.8).
Flatpak shows the correct version:
```
$ flatpak remote-info flathub org.telegram.desktop

Telegram Desktop - Telegram Desktop messenger

        ID: org.telegram.desktop
       Ref: app/org.telegram.desktop/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 1.9.9
   License: GPL-3.0
Collection: org.flathub.Stable
  Download: 22.0 MB
 Installed: 46.2 MB
   Runtime: org.kde.Platform/x86_64/5.13
```
And so does GNOME Software.

CC @grulja

**Comment by barthalion** [comment]
```
Feb 01 13:52:34 webapps.flathub.org podman[22274]: 2020-02-01 13:52:34.464  WARN 6 --- [pool-2-thread-1] o.flathub.api.service.UpdateServiceImpl  : org.telegram.desktop has incomplete appdata and won't be added/updated in the webstore. Issues found:
Feb 01 13:52:34 webapps.flathub.org podman[22274]: 2020-02-01 13:52:34.464  WARN 6 --- [pool-2-thread-1] o.flathub.api.service.UpdateServiceImpl  :   - component.icon is null
```

You need to specify `<launchable>` pointing to actual desktop file.

**Comment by gasinvein** [comment]
@barthalion AFAIK there wasn't a `<launchable>` tag ever before. Why did it work fine for previous versions?

**Comment by TingPing** [comment]
Without a `launchable` appstream goes into guessing mode. Does the `id` end in `.desktop`, look for it automatically, etc. Its fragile, implicit, and could have changed.

**Comment by gasinvein** [comment]
@barthalion @TingPing Something is not right here. We have desktop-id `org.telegram.desktop.desktop` in the appdata https://github.com/flathub/org.telegram.desktop/blob/4acb6b6d45fe349e36bb860799aed8ce4bf03e3a/patch/telegram-appdata-launchable.patch#L8-L10
While in the merged appstream on flathub there is `org.telegram.desktop` (without another `.desktop`):
```xml
<launchable type="desktop-id">org.telegram.desktop</launchable>
```
