### ISSUE TITLE
icons do not appear

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.telegram.desktop#14]
![captura de tela de 2017-11-20 20-04-47](https://user-images.githubusercontent.com/26097419/33044081-9a30e9a6-ce2e-11e7-969f-ebee59b9f5e1.png)

**Comment by TingPing** [comment]
What version of `flatpak`?

**Comment by grulja** [comment]
What desktop do you use?

**Comment by LeandroStanger** [comment]
@TingPing 
![captura de tela de 2017-11-21 08-21-09](https://user-images.githubusercontent.com/26097419/33067363-126414c8-ce95-11e7-87e2-08f1c28229a8.png)

**Comment by LeandroStanger** [comment]
@grulja  Endless OS 3.3.3

**Comment by LeandroStanger** [comment]
@nedrichards

**Comment by grulja** [comment]
Try to add kdeapps repo [1] and install icons and other stuff for better integration [2].

[1] - https://distribute.kde.org/kdeapps.flatpakrepo
[2] - https://community.kde.org/Guidelines_and_HOWTOs/Flatpak#Styles_and_integration_with_other_desktops

**Comment by TingPing** [comment]
Current versions of Flatpak mount host icons.

**Comment by TingPing** [comment]
@grulja BTW I tried following that guide in general but on GNOME I cannot figure any way to set Qt Flatapks to use Adwaita.

**Comment by grulja** [comment]
It should work automatically, but I just found out that Adwaita icons extension is missing in kdeapps repository, we will fix that and then you can try it again.

**Comment by nedrichards** [comment]
This will be resolved by Endless OS 3.3.5 which upgrades to Flatpak 0.10.1. When that's available @LeandroStanger can comment and close.

**Comment by LeandroStanger** [comment]
problem fixed
![captura de tela de 2017-12-12 08-33-10](https://user-images.githubusercontent.com/26097419/33880120-bfd0f4e0-df17-11e7-8927-cc7df8007c31.png)
