### ISSUE TITLE
Support for system fonts

### ISSUE THREAD

**Issue by Seqularise** [flathub/org.telegram.desktop#149]
As of now, flatpak version doesn't use system fonts, is that a flatpak limitation or problem is on telegram side?

**Comment by gasinvein** [comment]
It's a packaging option. Telegram can either use system or built-in fonts. We are building Telegram with built-in fonts to match Snap and official binary behavior.

**Comment by Seqularise** [comment]
ohh, i see your point, its important for cross platform application to preserve branding
Maybe its possible to import the custom fonts feature from kotatogram until it would be done by tdesktop themselves

**Comment by ilya-fedin** [comment]
This option is just for separate font packaging. This issue should be reported for upstream, as upstream forces open sans. It is weird to override or patch functionality. When I installing an app from flatpak, I want to use a version without any changes, from the developer as-is.

**Comment by ilya-fedin** [comment]
Well, this issue is not for flatpak package
