### ISSUE TITLE
[out-of-date] 1.2 is out

### ISSUE THREAD

**Issue by andrevmatos** [flathub/org.telegram.desktop#16]
Please, update

**Comment by grulja** [comment]
I was working on the update couple of hours today, but unfortunately failed. Telegram started using some C++17 stuff and we apparently have older GCC than telegram requires now.

**Comment by Barthalion** [comment]
I wonder if we should try to provide extension with newer toolchain. Any thoughts? @TingPing @nedrichards @alexlarsson

**Comment by Barthalion** [comment]
@grulja, could you push your 1.2 changes to separate branch?

**Comment by grulja** [comment]
I pushed my changes to "telegram-latest" branch. It doesn't build, fails now probably on something else than on C++17 stuff as I updated it to 1.2.6 now, but I didn't really look into it, I just made sure that patches apply.

**Comment by Barthalion** [comment]
Unfortunately fixing the code is beyond me (template changes were easy, but sudden `constexpr` available from gcc 7 is beyond me) so I will look at making the extension instead.

**Comment by Barthalion** [comment]
I pushed some minor changes to `telegram-latest` branch that will fix the build once gcc7 SDK extension is available. However Telegram fails to start via launcher that sets TMPDIR for some reason, works fine when omitted.

**Comment by Barthalion** [comment]
Works if TMPDIR is set to $XDG_RUNTIME_DIR though. @TingPing, is it okay to use it that way?

**Comment by Barthalion** [comment]
To answer myself, it's not okay, as it's not shared so user can start multiple instances of Telegram.

**Comment by grulja** [comment]
@Barthalion good work 👍

**Comment by TingPing** [comment]
> To answer myself, it's not okay, as it's not shared so user can start multiple instances of Telegram.

This is very late and I see you removed this but I'm confused why. $XDG_CACHE_HOME *is* a shared and readable path for Telegram itself.
