### ISSUE TITLE
Co-maintainer request

### ISSUE THREAD

**Issue by gasinvein** [flathub/org.telegram.desktop#160]
@barthalion @grulja I'd like to add @ilya-fedin to collaborators for this repo, if @john-preston doesn't have any objections. He's an active dev and is very well aware of ongoing Telegram updates.

**Comment by grulja** [comment]
+1 from me, I have seen @ilya-fedin contributing to Qt and Telegram.

**Comment by barthalion** [comment]
Done. @ilya-fedin, please make sure to accept your invite at https://github.com/flathub/org.telegram.desktop/invitations.
