### ISSUE TITLE
Flatpak Telegram under Wayland?

### ISSUE THREAD

**Issue by fourstepper** [flathub/org.telegram.desktop#169]
Hello,

Is it possible to run flatpak telegram under wayland?

flatpak run org.telegram.desktop --env=QT_QPA_PLATFORM=wayland nor setting -platform wayland results in a wayland-native telegram runtime

I am on Sway 1.4

**Comment by ilya-fedin** [comment]
> flatpak run org.telegram.desktop --env=QT_QPA_PLATFORM=wayland nor setting -platform wayland results in a wayland-native telegram runtime

`flatpak run --env=QT_QPA_PLATFORM=wayland org.telegram.desktop` works for me

**Comment by gasinvein** [comment]
I guess it should be `wayland-egl`, not just `wayland`.

**Comment by ilya-fedin** [comment]
> I guess it should be `wayland-egl`, not just `wayland`.

Both are working

**Comment by fourstepper** [comment]
@ilya-fedin Thanks - your command worked

Is it possible to set this for each app launch?

**Comment by ilya-fedin** [comment]
`flatpak override --env=QT_QPA_PLATFORM=wayland org.telegram.desktop`

**Comment by fourstepper** [comment]
Thanks for the quick help. I will have to learn up on how flatpak works in more detail.
