### ISSUE TITLE
Missing app icon

### ISSUE THREAD

**Issue by BrokeRU** [flathub/org.telegram.desktop#17]
Ubuntu 16.04 LTS
Flatpak 0.10.1
Telegram 1.1.23
![2017-12-15 11-21-06](https://user-images.githubusercontent.com/9129071/34029557-043c7c92-e18b-11e7-8f73-bb969ae61a31.png)

**Comment by jurf** [comment]
Is this still happening?

**Comment by BrokeRU** [comment]
@jurf no, now it's ok
