### ISSUE TITLE
Enabling wayland back

### ISSUE THREAD

**Issue by aleixpol** [flathub/org.telegram.desktop#170]
We are forcing QT_QPA_PLATFORM=xcb right now. We don't need to live like this forever.

I don't know what needs to happen for it to get back to native, is it documented somewhere?

**Comment by ilya-fedin** [comment]
https://github.com/flathub/org.telegram.desktop/issues/133

**Comment by ilya-fedin** [comment]
TL;DR I don't like this forcing of X11, I proposed to blacklist only Gnome if it has some problems, @gasinvein implemented that, but he said that he won't merge this until @grulja will tell his opinion

**Comment by gasinvein** [comment]
To decide if we should enable wayland by default or not, let's summarize - when Telegram works well on it and when it doesn't? From what I know, it works well on sway/wlroots (#169), but have glitches on (probably older) Gnome. What's about KDE?

**Comment by aleixpol** [comment]
Works fine of KDE Plasma on Wayland, never had an issue myself.
