### ISSUE TITLE
Telegram version 2.3.2 fail to detect my laptop's camera

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.telegram.desktop#185]
Hi. I updated to version 2.3.2 flatpak. I can receive camera call from a remote who contact me if she/he use his camera (from heir/his mobile for example). But I can not send him a video call because Telegram on my system (Fedora 32 X64 bit Cinnamon edition) can not detect my camera !

When I use make a video call (try to activate camera, I receive message inform me that no camera detected !

Is this related to permissions or it is like the case of qTox flatpak - see:
https://github.com/qTox/qTox/issues/6059#issuecomment-665489830
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2979

If it is the same of qTox case, then we are now at RC-1 - see:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases

Best.

**Comment by gasinvein** [comment]
Try running with `flatpak run --device=all org.telegram.desktop` and check if it works.

**Comment by Nokia808** [comment]
@gasinvein 
Yes it working with --device=all
So, it is a permission issue. 
Please update the package to fix this.
