### ISSUE TITLE
how to make telegram in flatpak respect my font settings?

### ISSUE THREAD

**Issue by soredake** [flathub/org.telegram.desktop#187]
I tried copying my `fonts.conf` file to `/var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.14/active/files/etc/fonts` and `~/.var/app/org.telegram.desktop/config/fontconfig/`, nothing changed, i only want `hintstyle` to be `hintmedium`

**Comment by ilya-fedin** [comment]
Just created `~/.var/app/org.telegram.desktop/config/fontconfig//fonts.conf` with content
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>	
<fontconfig>
  <match target="font">
    <edit name="hintstyle" mode="assign">
      <const>hintnone</const>
    </edit>
  </match>
</fontconfig>
```
Works like a charm

**Comment by soredake** [comment]
Does not work for me :(
Kubuntu 20.04 flatpak 1.8.2

**Comment by ilya-fedin** [comment]
I have flatpak 1.8.1

**Comment by ilya-fedin** [comment]
Maybe you just don't see the difference?

**Comment by soredake** [comment]
![Screenshot_20200830_141906](https://user-images.githubusercontent.com/5204968/91657721-d6217900-eacb-11ea-91d7-630404679f1a.png)
![image](https://user-images.githubusercontent.com/5204968/91657728-e46f9500-eacb-11ea-872e-df0097781fa8.png)
On my monitor left (telegram from ppa) looks clearly better than right (telegram from flatpak)

**Comment by ilya-fedin** [comment]
telegram from ppa uses fontconfig from the distro, telegram from flatpak uses fontconfig from flatpak
Of course it will look differently, Ubuntu has patched fontconfig.

**Comment by soredake** [comment]
You are right, i forgot about that, freetype built with this [patch](https://sources.debian.org/patches/freetype/2.9.1-3+deb10u1/enable-subpixel-rendering.patch/) that enables subpixel rendering, seems there is no way to make telegram in flatpak look same.

**Comment by ilya-fedin** [comment]
Yeah, no way

**Comment by soredake** [comment]
Opened an issue https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1106
