### ISSUE TITLE
System Window Frame setting reverts back to default after idle or sleep

### ISSUE THREAD

**Issue by aia832003** [flathub/org.telegram.desktop#189]
![Screenshot from 2020-09-04 11-01-01](https://user-images.githubusercontent.com/11007827/92271838-1ad35880-eeae-11ea-88bd-c4f903b9959d.png)
![Screenshot from 2020-09-04 11-01-33](https://user-images.githubusercontent.com/11007827/92271840-1b6bef00-eeae-11ea-8861-e907a09b0ff6.png)

*Steps to reproduce*

    enable system window frame in Advanced settings
    window frames change to system fonts and theme
    let the device go to sleep or force sleep
    System frame reverts back default Telegram UI elements
    Completely closing Telegram and relaunches allows system setting to be reapplied for GTK Theme

*Expected behaviour*

Changing the setting for System Window Frame should respect the system GTK Theme and decorations even after app has been minimized to background processes or system sleep. This is only an issue on Wayland. X11 sessions seem to hold the setting regardless.

*Actual behaviour*

At some point while running as a non-focused window and/or device goes to sleep the Window Frame reverts back to Telegram default until app is completely closed or reboot.

*Operating system:*

Fedora 32 and Pop_OS! 20.04
Version of Telegram Desktop:
2.3.2

*Used theme:*
Adwaita on Fedora and Pop default theme

Not sure if this helps but here's the terminal output when launching with flatpak commmand:
flatpak run org.telegram.desktop
(process:2): Telegram-WARNING **: 12:44:09.565: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 12:44:09.568: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 12:44:09.568: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported
Gtk-Message: 12:44:09.673: Failed to load module "appmenu-gtk-module"
Gtk-Message: 12:44:09.787: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:44:09.787: Failed to load module "canberra-gtk-module"
Telegram-Message: 12:44:09.800: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open

**Comment by ilya-fedin** [comment]
Well... xD

**Comment by aia832003** [comment]
Lol. Thought it might be worth filing with the Flatpak build. Sorry if I'm blowing this up.

**Comment by gasinvein** [comment]
@aia832003 Try forcing XWayland always with `flatpak override --user --env=QT_QPA_PLATFORM=xcb org.telegram.desktop` and check if the problem persists.

**Comment by aia832003** [comment]
Thanks @gasinvein I just ran that and will see if it sticks.

**Comment by aia832003** [comment]
@gasinvein thanks for this tip. This seems to have solve my issue.
