### ISSUE TITLE
Receiving files is broken

### ISSUE THREAD

**Issue by aleixpol** [flathub/org.telegram.desktop#19]
I don't really know where files go and clicking on the file I received doesn't open the file to view.
I never had this problem with the native client.

**Comment by Barthalion** [comment]
Files are downloaded to `$XDG_DOWNLOAD_DIR/Telegram Desktop`. Opening files should work via portal; is it some particular filetype?

**Comment by aleixpol** [comment]
Telegram shows a (wrong) save dialog in `~/Downloads/Telegram Desktop/` that only has stuff that I've downloaded from telegram, I'm guessing it's containerised. I have no idea how to reach it from the rest of my software.

**Comment by grulja** [comment]
Hi Aleix, is this still reproducible?

**Comment by grulja** [comment]
Ok, it is, it was working for me with --filesystem=host. I assume I need to just change cache location somewhere. I will investigate it.

**Comment by grulja** [comment]
Maybe will be fixed with https://github.com/flathub/org.telegram.desktop/pull/58.

**Comment by aleixpol** [comment]
Yes, I car receive files now, thanks.
