### ISSUE TITLE
X session close after login

### ISSUE THREAD

**Issue by 0pendev** [flathub/org.telegram.desktop#191]
When trying to set my account, after entering my code, the X session closes.

Here are the logs :
`(process:2): Telegram-WARNING **: 15:04:58.098: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 15:04:58.099: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 15:04:58.099: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Telegram-Message: 15:04:58.238: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
The X11 connection broke (error 2). Did the X11 server die?`

I'm running it on sway. It works fine when using the one from my default package manager (latest OpenSuse Tumbleweed).

**Comment by ilya-fedin** [comment]
This is an upstream bug
