### ISSUE TITLE
Cursor bigger than usual

### ISSUE THREAD

**Issue by nahuelwexd** [flathub/org.telegram.desktop#199]
With the removal of the wrapper that forced Telegram Desktop to run under XWayland on GNOME, a small visual error appeared that may not be of great importance but is annoying anyway: the cursor is larger than normal.

It is solved by setting the cursor size manually using an environment variable (`XCURSOR_SIZE=24`), although I guess it is not ideal

**Comment by ilya-fedin** [comment]
This is a generic issue for all Qt applications
