### ISSUE TITLE
"Use system window frame" option missing

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.telegram.desktop#200]
It seems that there is no "Use system window frame" option available in Advanced Telegram settings when using the Flatpak version (on Wayland GNOME session).

**Comment by ilya-fedin** [comment]
Please, create non-flatpak-specific issues on upstream bugtracker (don't forget to search existing issues, including closed ones)

**Comment by subpop** [comment]
A workaround for this issue is to add an override to the `org.telegram.desktop` flatpak to block access to the wayland socket. `flatpak override org.telegram.desktop --nosocket=wayland`. This forces the process to use X11 through Xwayland, and you "get your title bars back".

**Comment by emanuelserpa** [comment]
Why telegram removed the option?

**Comment by gasinvein** [comment]
This option makes no sense on native Wayland - there is no such thing as "system windows frame" - each app has to draw its own.

**Comment by emanuelserpa** [comment]
Oh, I understand. 

I'm a GNOME user but what the GNOME devs are doing with Qt apps is so shitty...

**Comment by felipeborges** [comment]
Since upstream is not interested in solving this for wayland+gnome, can we have the flatpak defaulting to xwayland again?

https://github.com/telegramdesktop/tdesktop/issues/8734

**Comment by gasinvein** [comment]
@felipeborges You can make telegram flatpak default to xwayland yourself if you'd like, with
`flatpak override --user --env=QT_QPA_PLATFORM=xcb org.telegram.desktop`

**Comment by felipeborges** [comment]
yeah, sure, I have done that for quite some time, but that doesn't fix the issue for everyone.

**Comment by AsciiWolf** [comment]
I would also like the Telegram Flatpak to default to Xorg again. I like Wayland, but its support in Telegram is quite not in a good state. There are more issues, for example [this](https://github.com/flathub/org.telegram.desktop/issues/202) one or behavior of the telegram window that is displayed as a small window at the top of the screen and I have to manually resize/maximize it every time. There were no such problems when using Xwayland.

**Comment by gasinvein** [comment]
@felipeborges Well, those window frames might look bad, but it's the upstream design decision. Honestly, I don't think we should try to "fix" it.

Previously we were effectively reverting flatpak KDE SDK changes that alter upstream Qt behavior of defaulting to XWayland on Gnome, and it has proven to be problematic as well (the wrapper solution doesn't work for autostarted Telegram, and the finish-args solution is way too broad).

**Comment by AsciiWolf** [comment]
@gasinvein As I said, it is not just the window frame. There are at least three issues that are happening only on Wayland.

**Comment by felipeborges** [comment]
fair enough, I wonder what percentage of Telegram desktop users are running GNOME+Wayland vs. any other combination. Are there stats?

**Comment by AsciiWolf** [comment]
> There are at least three issues that are happening only on Wayland.

**Correction:** At least five issues.

Another two Wayland-only issues:
https://github.com/flathub/org.telegram.desktop/issues/203
https://github.com/flathub/org.telegram.desktop/issues/209

**Comment by gasinvein** [comment]
@AsciiWolf Most of those wayland-specific issues are either generic Qt issues or come from Mutter issues, this, affecting multiple Qt apps, not only Telegram. Just [search](https://github.com/search?q=org:flathub+QT_QPA_PLATFORM&type=code) flathub for `QT_QPA_PLATFORM` and see how many apps have to implement such a fix. If you ask me, this should be fixed at runtime level.

**Comment by ilya-fedin** [comment]
> Another two Wayland-only issues

I even can't reproduce #209

**Comment by gasinvein** [comment]
Ping @barthalion @grulja. What should we do for now? Leave things as they are and wait for a runtime-wide fix (and/or upstream Qt fixes)? Or stick back to XWayland for all users?

**Comment by ilya-fedin** [comment]
> Or stick back to XWayland for all users?

I don't understand why there should be any wrappers just because some users hitting bugs of their old mutter that affecting all Qt apps and because some users doesn't like GNOME's decision don't support xdg-decoration protocol, we can't fix GNOME

**Comment by AsciiWolf** [comment]
@ilya-fedin My mutter version is 3.38.1.

**Comment by ilya-fedin** [comment]
> My mutter version is 3.38.1.

Then you should check the issue on the official binary and report this properly to upstream, so that upstream can decide what to do with it.

**Comment by gasinvein** [comment]
@ilya-fedin I guess the official binary uses static Qt which defaults to xcb. Still, the cursor size issue should be reproducible with `QT_QPA_PLATFORM` set to `wayland` explicitly.

**Comment by ilya-fedin** [comment]
> Still, the cursor size issue should be reproducible with `QT_QPA_PLATFORM` set to `wayland` explicitly.

Cursor size? We discussed flickering, isn't it? Cursor size is a known Qt issue and could be easily solved with XCURSOR_ZISE variable.

**Comment by gasinvein** [comment]
@ilya-fedin It's the same for all wayland-specific issues, since Qt in the official binary doesn't use wayland by default.

**Comment by ilya-fedin** [comment]
@gasinvein Why are you saying the obvious?

**Comment by gasinvein** [comment]
Well, I believe @AsciiWolf, like other users of recent enough Mutter, doesn't experience flickering issue anyway.

**Comment by ilya-fedin** [comment]
Then I don't understand why @AsciiWolf told his mutter version

**Comment by AsciiWolf** [comment]
I thought @gasinvein was talking about all Wayland issues, not just this one.

**Comment by ilya-fedin** [comment]
So:
#202 is a generic Qt issue
#203 is an old mutter issue that affect all Qt apps
#209 is not confirmed and looks like reporter went MIA

I don't see any reason to force XWayland.

**Comment by AsciiWolf** [comment]
What about the other three issues that I have talked about in my first comment?

**Comment by ilya-fedin** [comment]
What first comment are you talking about?

**Comment by AsciiWolf** [comment]
Sorry, I was on my mobile phone. I was talking about [this](https://github.com/flathub/org.telegram.desktop/issues/200#issuecomment-722366361) comment.

The first issue is this (#200) one, but I now see that you already mentioned it in your previous comment, sorry.
The second issue is the mouse cursor one (#202).
The third issue is weird behavior of the telegram window that I mentioned in the linked comment (I did not report it yet).

**Comment by ilya-fedin** [comment]
> The second issue is the mouse cursor one (#202).

I mentioned it as well

> The third issue is weird behavior of the telegram window that I mentioned in the linked comment (I did not report it yet).

Wayland doesn't have a protocol to position windows, initial window position is completely in compositor responsibility.

**Comment by AsciiWolf** [comment]
Regarding the window size/position issue, this appeared in my system journal while moving the Telegram window:
```gnome-shell[1875]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed```

So maybe it is actually a gnome-shell issue.

**Comment by kowalski7cc** [comment]
The strange thing is that these issues with TDesktop you don't find in other QT apps, like Dolphin or Kdenlive from Flathub (`flatpak run --env=QT_QPA_PLATFORM=wayland org.kde.kdenlive`) or Kleopatra from RPM (Running on Wayland too):
- Window opens correctly
- Window decoration get drawn correctly (It follows the correct gnome Adwaita theme)
- Cursor doesn't get bigger/smaller randomly

**Comment by ilya-fedin** [comment]
> Window decoration get drawn correctly (It follows the correct gnome Adwaita theme)

It could be only QGnomePlatform that tries to simulate Adwaita titlebar. It doesn't have shadows unlike the real native titlebar and won't change if you change GTK theme to something non-stdard.

tdesktop couldn't use QGnomePlatform due to its custom GTK integration to provide a dialog with image preview, getting GTK settings (dark mode, icon theme, titlebar buttons) and workaround the Qt clipboard bug: https://bugreports.qt.io/browse/QTBUG-56595.

> Window opens correctly

Can't say something about that, tdesktop opens correctly for me on Weston and Plasma with Wayland in a VM

> Cursor doesn't get bigger/smaller randomly

Looks like QGnomePlatform sets cursor size with a hack: https://github.com/FedoraQt/QGnomePlatform/blob/d5a01ea00ef49c22fa4f623495cd0d31e991a02e/common/gnomehintssettings.cpp#L257-L261

**Comment by kowalski7cc** [comment]
Edit: I tried adding the override to Kdenlive and start from gnome application list instead of the cli and got there too the cursor size issue, id I found how to fix it:
- On kdenlive you need to change `XDG_CURRENT_DESKTOP=kde` to  `XDG_CURRENT_DESKTOP=gnome`
- On TDesktop I fixed it with `--env=XDG_CURRENT_DESKTOP=gnome --env=TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1`

Now the TDestop remaining issues are the windows opening and the decoration

**Comment by ilya-fedin** [comment]
>     * TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY

I hope you read the warning

**Comment by grulja** [comment]
> tdesktop couldn't use QGnomePlatform due to its custom GTK integration to provide a file dialog with image preview, getting GTK settings (dark mode, icon theme, titlebar buttons) and workaround the Qt clipboard bug: https://bugreports.qt.io/browse/QTBUG-56595.
> 

QGnomePlatform now uses FileChooser portal when possible by default.

**Comment by ilya-fedin** [comment]
> QGnomePlatform now uses FileChooser portal when possible by default.

It's probably doesn't make so much difference since it always been used automatically until QT_QPA_PLATFORMTHEME is set? :thinking:

**Comment by ilya-fedin** [comment]
The biggest thing here is workaround for the Qt clipboard bug. The bug makes tdesktop UX terrible since image copypasting is a very frequent operation in a messenger.

**Comment by grulja** [comment]
> > QGnomePlatform now uses FileChooser portal when possible by default.
> 
> It's probably doesn't make so much difference since it always been used automatically until QT_QPA_PLATFORMTHEME is set?

Right, it will not make difference in case of Flatpak.

> The biggest thing here is workaround for the Qt clipboard bug. The bug makes tdesktop UX terrible since image copypasting is a very frequent operation in a messenger.

Is this something we can also fix in QGnomePlatform?

**Comment by ilya-fedin** [comment]
> Is this something we can also fix in QGnomePlatform?

Unlikely, it's on platform plugin level (a bug in xcb platform).
