### ISSUE TITLE
Mouse pointer is too big in Flatpak Telegram window on Wayland

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.telegram.desktop#202]
I am not sure if this issue is Flatpak specific or not. Mouse pointer seems to be double in size when being in Telegram window on my Fedora 32 system with GNOME Wayland session.

**Comment by ilya-fedin** [comment]
This is a result of the fact that wayland doesn't have a protocol to get cursor size and each toolkit has its own default cursor size.
https://bugreports.qt.io/browse/QTBUG-67579
