### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by n3vu0r** [flathub/org.telegram.desktop#203]
I'm using Telegram for quite some time now on a Debian Buster with Gnome desktop. Either with the last update of Telegram or with the slightly previous updates of the Flathub KDE/Gnome platform packages, Telegram became unusable. The GUI is flickering and not correctly refreshing and the mouse became a strange left handed icon.

Let me know if you need more details.

**Comment by gasinvein** [comment]
ACAIK Telegram had such problems on native Wayland with older Mutter, probably it's your case? Try focing it to use XWayland with `flatpak run --env=QT_QPA_PLATFORM=wayland-egl org.telegram.desktop`.

**Comment by n3vu0r** [comment]
Thanks for the quick response. Yes, I'm using Wayland and Gnome.

It didn't help. I also tried some other flags:

```
flatpak run --env=QT_QPA_PLATFORM=wayland-egl --env=TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1 --env=TDESKTOP_DISABLE_TRAY_COUNTER=1 --env=XCURSOR_SIZE=24 org.telegram.desktop
error: : cannot open
error: : cannot open
error: : cannot open
QCoreApplication::postEvent: Unexpected null receiver
```

It's still flickering.

**Comment by gasinvein** [comment]
Oh, sorry, my bad, it should be `QT_QPA_PLATFORM=xcb`. I've posted command that does quite the opposite - forces native wayland.

**Comment by n3vu0r** [comment]
Ahh, haven't noticed :D That does the trick, now it's working again. Thanks a lot!

**Comment by gasinvein** [comment]
Also you can do `flatpak override --user --env=QT_QPA_PLATFORM=xcb org.telegram.desktop` to set the env var for Telegram permanently.

**Comment by n3vu0r** [comment]
Just wanted to do that, thanks for the solution.

**Comment by jurf** [comment]
I am not sure if Wayland should be enabled by default if it still has issues like this.

**Comment by ilya-fedin** [comment]
> Telegram had such problems

This is not a Telegram issue, but a generic Qt issue

> I am not sure if Wayland should be enabled by default if it still has issues like this.

Tell that to the KDE runtime maintainers: https://github.com/KDE/flatpak-kde-runtime/blob/qt5.15lts/patch/qtbase-use-wayland-on-gnome.patch

**Comment by gasinvein** [comment]
So what do we have? Forcing XWayland for all Gnome users is bad, especially since for some of them Wayland works better (hidpi, etc). Leaving users of older Mutter (pre-3.32, I guess) with flickering issue is also bad.
I see only one universal approach - somehow check Mutter version on startup and force XCB platform only if it's actually needed.

**Comment by ilya-fedin** [comment]
Since the issue is a generic Qt issue, I think this should be handled at runtime level.

**Comment by jurf** [comment]
I wonder about that. Telegram on Wayland currently has some bugs I haven’t reported yet, but I’m not sure if they’re a bug on the side of the runtime or Telegram. E.g. the mouse cursor scales to 2× its size sometimes, I also experienced a crash when videocalling. I’ll look into it further, but if there are multiple Telegram-specific issues, I’d argue for locally disabling Wayland.

**Comment by ilya-fedin** [comment]
> E.g. the mouse cursor scales to 2× its size sometimes

This is a generic Qt issue as well
