### ISSUE TITLE
Media preview is wrong size, possibly affected by either multi-monitor or mixed HiDPI scaling levels

### ISSUE THREAD

**Issue by kode54** [flathub/org.telegram.desktop#211]
I was using the latest Telegram Desktop stable, 2.4.6, on Fedora 33, using the default Gnome desktop. It was running as a Wayland session on my AMD RX 480, with DP-1 on the left on a 3840x2160@60Hz monitor, and DP-2 on the right with a 1920x1080@60Hz monitor. The DP-1 output is set to 200% scale, while the DP-2 is set to 100%.

Telegram appears to be different from the native build I have used on Arch Linux before, wherein the scale settings only go from 100% to 150%, and default to 100%, even on the 200% display. It also appears to scale correctly between the two different scaled displays.

The problem that occurs, is that media previews, clicked images or videos, appear to scale to double the size of the actual desktop scale, resulting in a background that fills the primary display (DP-1), but the image or video is centered toward the bottom right of the DP-1 display, as if it is either the top left quadrant of a display which is twice as large in both dimensions.

I cannot compare to a native version yet, as the only way to do so on Fedora would be to run the AppImage type build, as Fedora does not package native versions in its repositories.

**Comment by ilya-fedin** [comment]
This place only for packaging issues, your issue doesn't sound like that one...

**Comment by kode54** [comment]
Well, it is a packaging issue that it behaves differently from a native package. Unless this is just an inherent limitation of Flatpak.

**Comment by ilya-fedin** [comment]
Qt in flatpak runtime is patched to use Wayland by default on GNOME, did you check this with QT_QPA_PLATFORM=wayland on native package?

**Comment by ilya-fedin** [comment]
> as Fedora does not package native versions in its repositories

As far as I know, there are a package in rpmfusion repo

**Comment by ilya-fedin** [comment]
@kode54 no response, I assume we can close the issue?

**Comment by kode54** [comment]
Also happens in the RPMFusion package, so I guess it's either an upstream or Fedora issue. Does not happen on Arch, also Arch has zoom settings from 50% to 300% while both versions on Fedora have a scale from 100% to 150%. Gonna call this down to distribution packaging issues, and toss my Fedora install in the garbage.
