### ISSUE TITLE
Huge mouse cursor, no window borders and no option to have system titlebar when running Telegram on Wayland (Gnome)

### ISSUE THREAD

**Issue by pedrofleck** [flathub/org.telegram.desktop#214]
I know this is an old issue and it was fixed for most people, however, I still have this problem in my desktop (Radeon graphics), although I don't have it in my Intel laptop.
It was running without a problem on X11, however, when using a Wayland session, the mouse cursor is huge, I can't change the titlebar to follow system and there are no window border. Running with "QT_QPA_PLATFORM=xcb" does fix it.
I'm running Fedora 32 with Gnome 3.36.

**Comment by ilya-fedin** [comment]
All these problems have its own tickets, please search before opening new issues.
