### ISSUE TITLE
Monochromatic icon support

### ISSUE THREAD

**Issue by bellini666** [flathub/org.telegram.desktop#227]
Most (if not all) apps that have a tray icon use a monochromatic icon on the tray icon.

Would it be possible to use one here too?

**Comment by ilya-fedin** [comment]
This is just repository of a package, this is not a bug tracker of the app

**Comment by bellini666** [comment]
@ilya-fedin do you know where should I report this?

**Comment by ilya-fedin** [comment]
I don't think you should report this at all since tdesktop supports icon themes and you can just install icon theme that contains monochrome icons for tdesktop
