### ISSUE TITLE
Drag and drop to send files is broken

### ISSUE THREAD

**Issue by aleixpol** [flathub/org.telegram.desktop#23]
I used to drop screenshots from the screenshot application, now it doesn't work saying: `Could not send an empty file: /tmp/....` as the process probably doesn't see the file at all, yet this needs figuring out.

**Comment by jurf** [comment]
Yeah, it only works from some directories…

**Comment by TingPing** [comment]
Because it only has access to some directories. DnD doesn't hit the portal.

**Comment by aleixpol** [comment]
Still bad usability, the user shouldn't need to be aware of portals.

**Comment by TingPing** [comment]
Indeed, reported here: https://github.com/flatpak/xdg-desktop-portal/issues/99

**Comment by Mikaela** [comment]
Is it possible to somehow allow all flatpaks access specific screenshot directory? I tend to store all my screenshots in a specific directory containing nothing else and to send them with Telegram (or Discord), I have to copy them to my Downloads folder for it to work.

I tried to look for an issue about it in flatpak/flatpak, but didn't encounter anything relevant.

**Comment by TingPing** [comment]
@Mikaela *all*? No. Specific ones: `flatpak override --user --filesystem=home/screenshots org.example.app`

**Comment by Mikaela** [comment]
Thanks, I think I can manage with specific ones :)

**Comment by jurf** [comment]
I wonder if we should just `--filesystem=host` this until DnD is fixed properly, it’s really not good UX.

**Comment by tapir** [comment]
Does this work recursively? I would like to have it access to my home completely

**Comment by tapir** [comment]
Also this issue might be different than initially thought because sending files from the "Attach" icon works. Only drag and drop doesn't work. Just as a side note....

**Comment by jurf** [comment]
@tapir: not sure what you mean by recursively but you can achieve that with a simple `flatpak override --user --filesystem=home org.telegram.desktop`.

Also, yeah, attaching a file goes through a portal, so that works fine.

**Comment by nate2014jatc** [comment]
As a workaround, can your screenshot app load the images into your clipboard?
I've never had issues doing that before

**Comment by THEBOSS619** [comment]
> @tapir: not sure what you mean by recursively but you can achieve that with a simple `flatpak override --user --filesystem=home org.telegram.desktop`.
> 
> Also, yeah, attaching a file goes through a portal, so that works fine.

works wonderfully well

**Comment by teohhanhui** [comment]
Is this still being considered?

https://github.com/flathub/org.telegram.desktop/issues/23#issuecomment-439492449

**Comment by gasinvein** [comment]
`--filesystem=host` seems way too broad. Maybe add `--filesystem=xdg-{pictures,documents,etc...}` instead?

**Comment by ilya-fedin** [comment]
> Maybe add `--filesystem=xdg-{pictures,documents,etc...}` instead?

I think we should just wait until toolkits implement the FilleTransfer portal. I believe that we shouldn't add permissions until this is really necessary.

**Comment by gasinvein** [comment]
Is there some ongoing work to implement it in Qt? I'm not aware of it, maybe @grulja or @aleixpol could give an update?

**Comment by soredake** [comment]
For some reason dnd started working, without additional permissions, tried sending from multiple locations (/etc /media /home), all working, same for saving files.

**Comment by joe733** [comment]
I'm not sure if this is the exact way to solve this issue but it works for me.. (at least for now)

Telegram: 2.5.8
Flatpak: 1.8.3

I had an [issue with org.freedesktop.Platform.GL.default](https://github.com/flatpak/flatpak/issues/4108), which was solved by running `sudo flatpak repair --user`. After this I ran `flatpak update` and then I discover that I can drag and drop files to telegram.

![Screenshot from 2021-02-12 08-46-56](https://user-images.githubusercontent.com/38415384/107727173-b21bc200-6d10-11eb-998a-995ab2e9ce8c.png)

**Comment by gasinvein** [comment]
@joe733 DnD works from directories that Telegram flatpak has access to, e.g. `~/Download`. Is that your case?

**Comment by joe733** [comment]
Ooh my bad 🤦🏻‍♂️, I should've double checked. You're right, DnD possible from the ones this Flatpak has access to, not from others.

**Comment by joe733** [comment]
Hey, it's a bit different...

> Click on image to enlarge 

Flatpak Apps | Flatpak Version: 1.8.3

|  | Telegram | Slack | Firefox | Chromium |
| --- | --- | --- | --- | --- |
| **File Chooser** | ![WhatsApp Image 2021-02-20 at 08 44 10](https://user-images.githubusercontent.com/38415384/108582316-6d1f0d80-7358-11eb-9adc-85cb961256ae.jpeg) | ![WhatsApp Image 2021-02-20 at 08 42 24](https://user-images.githubusercontent.com/38415384/108582297-57a9e380-7358-11eb-8196-d1c77cd2aacc.jpeg) | ![WhatsApp Image 2021-02-20 at 08 47 01](https://user-images.githubusercontent.com/38415384/108582329-8b850900-7358-11eb-9391-9be67aaf0436.jpeg) | ![image](https://user-images.githubusercontent.com/38415384/108582508-da7f6e00-7359-11eb-82bd-fca94f60ee16.png) |
| **DnD** | works only from `~/Downloads` | works anywhere from `~/` | works only from `~/Downloads` | works anywhere from `~/` |
| **Upload / Attach** | works anywhere from `~/` | works anywhere from `~/`  | works anywhere from `~/` | works anywhere from `~/` |

How did `Slack` & `Chromium` do it?

> By the way the file chooser from `Telegram` & `Firefox` is usually seen in non-flatpak application.

**Comment by ilya-fedin** [comment]
I guess they just have access to entire home in their default permissions

**Comment by joe733** [comment]
Hm.. could that be a workaround, until flatpak resolves this issue.. 🤔

**Comment by ilya-fedin** [comment]
> could that be a workaround,

I'm afraid it couldn't. I'm not sure if we're allowed to make such big holes in the sandbox. Chromium & Slack might have some special exclusion to do that...

> until flatpak resolves this issue

It's not flatpak, it's Qt. Qt should support FileTransfer portal for that, but looks like they don't have any plan to do that, since there are no such Epic on their bugtracker. I.e. this looks like something that never will be adressed (probably due to a bad design flatpak folks chosen for that, both sides of DnD should support the portal or it won't work). Probably flatpak folks are ok with that since their favorite gtk4 supports this. ¯\_(ツ)_/¯

**Comment by soredake** [comment]
I hope eventually someone will report this to qt bugtracker.

**Comment by mmiller7** [comment]
Is there any way to fix this so it just works properly nomater where the file is?  I shouldn't have to spend forever guessing what directory may/may not be allowed or copying files to/from an external disk -- if the logged in user has access I should be able to send it.

In my case selecting the "attach" and then a file is not a working fix, it crashes the entire UI/program and I had to reboot the whole computer to get Telegram un-stuck since even clicking close didn't work.

I guess I'll go back to manually downloading the binary...

**Comment by ilya-fedin** [comment]
> Is there any way to fix this so it just works properly nomater where the file is?

No way. You can allow home access, but you still won't be able to drag'n'drop from removable media.

**Comment by gasinvein** [comment]
> you still won't be able to drag'n'drop from removable media

Well, removable media can be allowed with `host` (instead of `home`) or `/run/media`.

**Comment by ilya-fedin** [comment]
> Well, removable media can be allowed with `host` (instead of `home`) or `/run/media`.

Doesn't host filesystem mount to some subfolder rather than process root? I guess it won't be able to map the path.

**Comment by ilya-fedin** [comment]
/run/media will though I guess

**Comment by gasinvein** [comment]
> Doesn't host filesystem mount to some subfolder rather than process root?

It mounts home along with `/mnt`, `/run/media` and some other directories to at the same paths they're on host, so it should do for removable media.

**Comment by mmiller7** [comment]
Seems to depend which OS flavor, my Mint 20 system puts removable media under /media/<username>/<media-label>
Then the <media-label> directory is created with read/write/execute permissions owner/group of <username> user.

I think RHEL type systems may put media under /run somewhere (been a while) but Mint is Ubuntu/Debian based and seems to put it under /media.

At this point I also have everything broken entirely and can't open it at all because I tried the command substituting / for "home"  `flatpak override --user --filesystem=/ org.telegram.desktop` thinking this may allow everything and it gives no errors but also Telegram silently no longer opens at all and no idea how to debug that.

Seems like the flatpak implementation is rather badly broken compared to the manual extracted binaries, it sounded like it was supposed to be easier but it sure seems worse in every way.

**Comment by ilya-fedin** [comment]
> `flatpak override --user --filesystem=/ org.telegram.desktop` thinking this may allow everything and it gives no errors but also Telegram silently no longer opens at all and no idea how to debug that.

You replace virtual FS with your host one, so tdesktop binary no longer exists and there's nothing to launch

**Comment by ilya-fedin** [comment]
> Seems like the flatpak implementation is rather badly broken compared to the manual extracted binaries

Yeah, new APIs are very slowly being consumed by toolkit authors, so you have to deal with sandboxing disadvantages until all that will be really ready

**Comment by mmiller7** [comment]
> > `flatpak override --user --filesystem=/ org.telegram.desktop` thinking this may allow everything and it gives no errors but also Telegram silently no longer opens at all and no idea how to debug that.
> 
> You replace virtual FS with your host one, so tdesktop binary no longer exists and there's nothing to launch

And I take it there's no validation or undo?

**Comment by ilya-fedin** [comment]
> And I take it there's no validation or undo?

I don't understand your question

**Comment by gasinvein** [comment]
`--filesystem=/` is explicitly prohibited, since if it worked, it would inevitably break the application. flatpak should print something like this when you request it:
>error: --filesystem=/ is not available, use --filesystem=host for a similar result

**Comment by mmiller7** [comment]
> > And I take it there's no validation or undo?
> 
> I don't understand your question

When I ran that I got no errors.  When I tried to launch Telegram now, I get no errors and no program.

It doesn't work and doesn't say why or how to reverse it

**Comment by mmiller7** [comment]
> `--filesystem=/` is explicitly prohibited, since if it worked, it would inevitably break the application. flatpak should print something like this when you request it:
> 
> > error: --filesystem=/ is not available, use --filesystem=host for a similar result

it did not, it simply accepted it and now nothing works with no errors.

**Comment by gasinvein** [comment]
> how to reverse it

Users' overrides are stored in `~/.local/share/flatpak/overrides/org.telegram.desktop`. Removing this file will remove overrides.

**Comment by mmiller7** [comment]
> > how to reverse it
> 
> Users' overrides are stored in `~/.local/share/flatpak/overrides/org.telegram.desktop`. Removing this file will remove overrides.

Ah, ok.  Found and deleted that at least now it launches.  Shame this is so convoluted.

**Comment by ilya-fedin** [comment]
`flatpak override --user --reset org.telegram.desktop`

**Comment by ilya-fedin** [comment]
@gasinvein I lost any hope in that Qt will implement FileTransfer protocol, so I'll add `--filesystem=host` if you're not against that

**Comment by teohhanhui** [comment]
That's really overkill. The typical user would not need to drag and drop files from any location. Of course, the power user could still add that override themselves if they really need that.

I'd think adding more XDG directories should suffice:
* `xdg-download` (existing permission)
* `xdg-pictures`
* `xdg-videos`
* any others as appropriate...

https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html#filesystem-permissions

**Comment by ilya-fedin** [comment]
That would lead to a very bad UX when user can DnD only from certain directories, while can't from e.g. home or removable media. It's even worse than the current situation, since currently DnD is not possible at all, so it's not so confusing.

**Comment by gasinvein** [comment]
@ilya-fedin I guess we have no other option at this point? Even if allowing all files for DnD, it certainly should be read-only. There is a large difference between `host` and `host:ro` - the former allows trivial sandbox escape, while the later (presumably) doesn't.

**Comment by ilya-fedin** [comment]
Yeah, `host:ro` should be ok, since FileChooser portal is implemented by Qt at least. If you're ok with that, I'll commit the fix.

**Comment by gasinvein** [comment]
Well, I don't like it, but I'm not strictly against it either. Let's hope we'll be able to remove it back some day.

**Comment by ilya-fedin** [comment]
@john-preston can you share your thoughts on this?

**Comment by john-preston** [comment]
I think we should add `host:ro` so that it works as expected by the majority of our users.

If I understand correctly the Electron-based messaging apps like Slack or Discord add `host` and for their users it "just works". I don't think UX on TDesktop should be any worse.

**Comment by gasinvein** [comment]
> If I understand correctly the Electron-based messaging apps like Slack or Discord add `host` and for their users it "just works". I don't think UX on TDesktop should be any worse.

Electron doesn't support filetransfer portal, thus, sending files isn't possible at all without direct filesystem access. Telegram, though, needs filesystem access only for drag-and-drop: sending arbitrary files works without it when selecting them via file-picker dialog.

**Comment by ilya-fedin** [comment]
> Electron doesn't support filetransfer portal

You meant FileChooser, I guess, FileTransfer is for DnD.

> Telegram, though, needs filesystem access only for drag-and-drop: sending arbitrary files works without it when selecting them via file-picker dialog.

It's still a poor UX.

**Comment by gasinvein** [comment]
> > Electron doesn't support filetransfer portal
> 
> You meant FileChooser, I guess, FileTransfer is for DnD.

Yes, but, well, it supports neither anyway.

Although they've switched to GtkFileChooserNative recently, so some next electron release (14?) should support FileChooser portal.

**Comment by john-preston** [comment]
@gasinvein This is correct. But in my comment I was talking about drag-n-drop and everything I said is still valid.

**Comment by gasinvein** [comment]
@john-preston Yeah, I agree that Telegram shouldn't have worse UX than electron-based messengers, it's just sad that a Qt-based app has to stick with the same insecure defaults as electron ones. Well, at least Telegram doesn't need r/w access.

**Comment by ilya-fedin** [comment]
Well, the only toolkit that can work in confined environment is gtk4. Even gtk3 doesn't support DnD in flatpak and they have no plan to backport support for it. It's a shame flatpak developers can't develop APIs in a way that won't require rewriting all the toolkits.

**Comment by aleixpol** [comment]
What protocol is GTK4 implementing for it to work?

**Comment by ilya-fedin** [comment]
@aleixpol https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.portal.FileTransfer.xml

**Comment by ilya-fedin** [comment]
That seem to be gtk4 implementation: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1244

**Comment by vchernin** [comment]
For future reference [this is the QT FileTransfer issue](https://bugreports.qt.io/browse/QTBUG-91357).

Hopefully some day someone works on it.

**Comment by ilya-fedin** [comment]
"The FileTranfer portal should explictly only be used when in a sandboxed app, as discussed here: https://github.com/flatpak/libportal/issues/33"

I see some logic error in that statement: if both sides of DnD must support FileTransfer protocol, such check will make it useless, won't it?

**Comment by vchernin** [comment]
> I see some logic error in that statement: if both sides of DnD must support FileTransfer protocol, such check will make it useless, won't it?

I think it should be fine, as the idea is the implementation should only be used when called by a sandboxed app. But the support must be present and working. So instead of being "optional" at compile time, it should only used when called by a sandboxed app. So if someone is not using sandboxed apps the FileTransfer portal will exist but not used.

Maybe I can reword those sentences:
> Implement support for the FileTranfer portal in Qt.
> 
> The FileTranfer portal should explictly only be used when called by a sandboxed app, as discussed here: flatpak/libportal#33

**Comment by ilya-fedin** [comment]
> So if someone is not using sandboxed apps the FileTransfer portal will exist but not used.

As far as I understand, FileTransfer portal must be used by both sides of DnD interaction: the unsunboxed app and the sandboxed app. And you can't know whether another side of DnD interaction is sandboxed or not, so you should always use FileTransfer implementation when initializing DnD. So, what you propose will just break DnD interaction.

**Comment by vchernin** [comment]
> So, what you propose will just break DnD interaction.

I see your logic, I am not really sure what the answer is here. I wonder how GTK4 handles this.

**Comment by ilya-fedin** [comment]
> I wonder how GTK4 handles this.

It uses portal whenever it's available, without checked whether environment is sandboxed or not
![изображение](https://user-images.githubusercontent.com/17829319/130292056-ac51ebfb-005f-4c50-bb77-f7d0c23e108c.png)

**Comment by vchernin** [comment]
> It uses portal whenever it's available, without checking whether environment is sandboxed or not

If that is indeed the case that sounds concerning, but it seems surprising. 

After all Matthias is the one who implemented FileTransfer into XDG Desktop Portal and GTK4, and according to the libportal issue is also the one not keen on using portals for non sandboxed apps.

Surely there must be a missing piece of info here right?

**Comment by ilya-fedin** [comment]
> Surely there must be a missing piece of info here right?

No, I see it pretty clean. If you don't believe me, you can look at the code on your own or ask gtk developers.

**Comment by vchernin** [comment]
Agreed, I think we should ask somewhere.

@gasinvein what do you think here? Should I make an xdg-desktop-portal issue? I would like to make sure the QT bug has accurate information, and this seems like a real discrepancy. If the GTK4 implementation was not done optimally we should note that in the QT bug, and a GTK issue should be reported too.

**Comment by ilya-fedin** [comment]
I don't think GTK4 implementation is not optimal btw, I think gtk developers are just being hypocritical.

**Comment by im-0** [comment]
```
New org.telegram.desktop permissions:
    file access [1]
```
Is there any way to disable this manually?

**Comment by vchernin** [comment]
> Is there any way to disable this manually?

There certainly is! Try using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) or `flatpak override`
