### ISSUE TITLE
Upload does not seem to be working.

### ISSUE THREAD

**Issue by aaashutosh** [flathub/org.telegram.desktop#231]
The upload option whether it be for uploading photos for profile picture or for sending files and attachments does not seem to open up. Drag and drop also seems to be broken.
Telegram version: 2.5.1 
Flatpak version: 1.10.1

**Comment by gasinvein** [comment]
Selecting a file to upload via file-picker should work fine. If `xdg-desktop-portal` running on your host system?
Drag-n-drop in Qt apps requires additional filesystem permissions currently, see #23

**Comment by aaashutosh** [comment]
Also, links don't seem to open even if you click on them.

**Comment by ilya-fedin** [comment]
You don't have xdg-desktop-portal. You must have it properly configured in order to run flatpak applications.
