### ISSUE TITLE
It does not start anymore

### ISSUE THREAD

**Issue by Pixelnarium** [flathub/org.telegram.desktop#234]
I am on ArchLinux with Sway as WM. For a test I removed ~/.var/app/org.telegram.desktop

$ flatpak run org.telegram.desktop 
```
(process:2): Telegram-WARNING **: 10:54:23.982: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 10:54:23.984: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 10:54:23.984: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).

(telegram-desktop:2): GLib-GIO-WARNING **: 10:54:26.382: Failed to execute child process ?update-desktop-database? (No such file or directory)
/usr/include/c++/10.2.0/optional:441: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = Window::Notifications::ManagerType; _Dp = std::_Optional_base<Window::Notifications::ManagerType, true, true>]: Assertion 'this->_M_is_engaged()' failed.
```

The line:
```(telegram-desktop:2): GLib-GIO-WARNING **: 10:54:26.382: Failed to execute child process ?update-desktop-database? (No such file or directory)```
vanishes on the second try.

Downgrading via:
```sudo flatpak update --commit=5fa7560e316c8a08cd7a26b45e68320eb5783abf77fdddf5968ae3e8b627385c org.telegram.desktop```

Makes it work again.

**Comment by gasinvein** [comment]
Sadly I can't test it with native sway due to Nvidia GPU, though it does work for me under sway with x11 wlroots backend.
Try full extracting full backtrace: install `org.telegram.desktop.Debug`, launch the app, and after it craches - run `flatpak-coredumpctl org.telegram.desktop` to get gdb shell in sandbox, then run `bt full`.

**Comment by Pixelnarium** [comment]
I attached the bt full output.

[gdb.txt](https://github.com/flathub/org.telegram.desktop/files/5897854/gdb.txt)

**Comment by gasinvein** [comment]
@ilya-fedin Does this ring a bell?

**Comment by ilya-fedin** [comment]
Looks like this is an effect of default compiler flags provided by runtime, we need to disabled them somehow, tdesktop is developed to work without flags like glibc assertions...

**Comment by ilya-fedin** [comment]
@Pixelnarium try a build from #235

**Comment by Pixelnarium** [comment]
I removed Telegram and installed the test version via the command in the pull request. Sadly this does not fix it. Same issue.

$ flatpak run --user org.telegram.desktop 
```
(process:2): Telegram-WARNING **: 08:47:46.306: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 08:47:46.308: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 08:47:46.308: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
error: : cannot open
error: : cannot open
error: : cannot open
/usr/include/c++/10.2.0/optional:441: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = Window::Notifications::ManagerType; _Dp = std::_Optional_base<Window::Notifications::ManagerType, true, true>]: Assertion 'this->_M_is_engaged()' failed.
```

$ flatpak info org.telegram.desktop 
```
Telegram Desktop - Telegram Desktop messenger

         Kennung: org.telegram.desktop
             Ref: app/org.telegram.desktop/x86_64/test
     Architektur: x86_64
           Zweig: test
         Version: 2.5.8
         License: GPL-3.0
        Ursprung: desktop-origin
        Sammlung: org.flathub.Stable.Build36686
    Installation: user
     Installiert: 68,1 MB
Laufzeitumgebung: org.kde.Platform/x86_64/5.15
             Sdk: org.kde.Sdk/x86_64/5.15

          Commit: 202dd596816c62d105e18f68c43b0d8c00800a9357fa3aad9cf2d46dfeb631e6
         Subject: Disable GLIBCXX assertions (0abeef31)
            Date: 2021-01-30 20:51:44 +0000
``'

**Comment by ilya-fedin** [comment]
meh... looks like this is not that easy. Does anyone know who may know how to disable hardening flags on flathub?

**Comment by gasinvein** [comment]
@ilya-fedin You can drop default cflags altogether by overriding them, set `"cflags": "-O2 -g"` and `"cflags-override": true` (similar for `cxxflags`) in `build-options`.

**Comment by ilya-fedin** [comment]
cflags don't matter there since the problem is with cxxflags...

**Comment by ilya-fedin** [comment]
I pushed new attempt to the same PR

@Pixelnarium please test when it will build

**Comment by ilya-fedin** [comment]
It is built

**Comment by Pixelnarium** [comment]
This one works :) Thank you for your fast help.
