### ISSUE TITLE
Missing tray icon on F33

### ISSUE THREAD

**Issue by plbpietrz** [flathub/org.telegram.desktop#237]
Hi,

I'm on a fresh vanilla Fedora 33 install with "Tray Icons: Reloaded" and Telegram icon is missing from the tray. Is this a bug or am I doing something wrong?

**Comment by gasinvein** [comment]
From the extension desctiption, looks like it provides legacy xembed tray. I'm not sure if Telegram even supposed to work with that. 
It should work fine with appindicator, though, so try `gnome-shell-extension-appindicator` instead.

**Comment by ilya-fedin** [comment]
>  I'm not sure if Telegram even supposed to work with that

It's supposed, but it won't work on Wayland because... you know, XEmbed is part of X11 protocol.

**Comment by plbpietrz** [comment]
> From the extension desctiption, looks like it provides legacy xembed tray. I'm not sure if Telegram even supposed to work with that.
> It should work fine with appindicator, though, so try `gnome-shell-extension-appindicator` instead.

This AppIndicator extension worked flawlessly so thank you very much for your help :wink:
