### ISSUE TITLE
Show in folder, fails to open file browser at the folder

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.telegram.desktop#25]
What happened:
1) Install telegram
2) Have a file sent to you that needs to be downloaded (eg video, document, non-compressed image)
3) Download the file by clicking on it
4) Right click there is an option "Show in folder", select it
5) Notice nothing happens

What I expected to happen:
At step 5 for the file browser to open at the download folder

Note that "Save File As.." works, so it is not the xdg-desktop-portal being totally broken. Also note I have yet to find any messages in the app or system log :-/

**Comment by TingPing** [comment]
I believe this is reported here: flatpak/xdg-desktop-portal#128

**Comment by aleb** [comment]
The fix has been merged, try again with flatpak 0.11.3

**Comment by ahayzen** [comment]
I can confirm with flatpak 0.11.3 this now works, therefore I'm closing the issue. There does seem to be a separate issue where the file manager or file chooser is launched behind the app - which is a bit irritating.
