### ISSUE TITLE
Two telegram sessions

### ISSUE THREAD

**Issue by emanuc** [flathub/org.telegram.desktop#253]
I start telegram desktop, I close it from the window, the telegram icon remains active in the GNOME status bar (I use the extension from the fedora33 repositories: gnome-shell-extension-appindicator.noarch), when I reopen the window from the dock ( dash to dock), another telegram session is started, thus having two active sessions.
No problem if I reactivate the window from the status bar: "open teelgram", in this case a session remains.
I have logs, hope they help: [https://pastebin.ubuntu.com/p/9T6Xt4C48h/](https://pastebin.ubuntu.com/p/9T6Xt4C48h/)

OS: fedora 33
Flatpak version: 1.10.2
telgram version:
flatpak info org.telegram.desktop 

> Telegram Desktop - Telegram Desktop messenger
> 
>           ID: org.telegram.desktop
>          Ref: app/org.telegram.desktop/x86_64/stable
>         Arch: x86_64
>       Branch: stable
>      Version: 2.7.1
>      License: GPL-3.0
>       Origin: flathub
>   Collection: org.flathub.Stable
> Installation: system
>    Installed: 71,5 MB
>      Runtime: org.kde.Platform/x86_64/5.15
>          Sdk: org.kde.Sdk/x86_64/5.15
> 
>       Commit: 69a97da43a30041495de7a2b588edfbcb11d5586f81be63433f544e0bde2f41a
>       Parent: 44e43366887d702237c975d1514b01cbcbfa236cfaa2864a0f0cb75fec629a37
>      Subject: Update tdesktop.git to 2.7.1 (a8e3c77c)
>         Date: 2021-03-20 20:42:50 +0000

![Schermata del 2021-04-15 14-57-31](https://user-images.githubusercontent.com/27281121/114872823-f6077200-9dfa-11eb-9ffc-07f5f42cd33b.png)

**Comment by ilya-fedin** [comment]
looks like it's https://github.com/KDE/flatpak-kde-runtime/commit/c80bf1bf101611a7447a0393907f27c38e3cbdad
@grulja

**Comment by gasinvein** [comment]
@ilya-fedin this commit didn't land yet in flathub repo (current build is of 13 Apr). I guess KDE/flatpak-kde-runtime@c80bf1b will actually fix the regression?

**Comment by ilya-fedin** [comment]
yeah, it's actually https://github.com/KDE/flatpak-kde-runtime/commit/43c8c8ac28d5d119a890b5431a22dbfa8b13803f
