### ISSUE TITLE
Latest update (2.7.2) disabled Wayland by default

### ISSUE THREAD

**Issue by xscd** [flathub/org.telegram.desktop#256]
Not sure if its intentional or not. Before Wayland was enabled by default.

**Comment by gasinvein** [comment]
Latest update switched to custom Qt, and Qt defaults to x11 on GNOME, so this is kinda intentional. You can switch back to Wayland via `flatpak override --user --env=QT_QPA_PLATFORM=wayland org.telegram.desktop` if you'd like.

**Comment by ilya-fedin** [comment]
Yeah, it's intentional. We finally switched to custom Qt build and there's no this Fedora's ugly patch anymore to force Wayland on GNOME.
