### ISSUE TITLE
Regression: broken composed input on wayland compositors that support text-input-v2

### ISSUE THREAD

**Issue by aleixpol** [flathub/org.telegram.desktop#258]
As you moved away from org.kde.Platform you lost the following change which regresses at least on Plasma. 
I8601f5d7ae21edf4b3a1191fa75877286e505588

**Comment by gasinvein** [comment]
Can/should we cherry-pick the relevant changes?

**Comment by aleixpol** [comment]
Well of course, I'd say you should. I'd suggest you follow the KDE Patch Collection for Qt 5.
https://community.kde.org/Qt5PatchCollection
