### ISSUE TITLE
Wrong icon under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.telegram.desktop#27]
My screenshot shows telegram running on KDE Plasma 5.12 Wayland session, Arch Linux.

![telegram flatpak](https://user-images.githubusercontent.com/15967631/36152626-c88f5c08-10b2-11e8-91de-6bf819cc6e79.png)

**Comment by TingPing** [comment]
This is because `rename-icon` is used but somehwere in code it refers to the old name.

**Comment by Alexander-Wilms** [comment]
Would `copy-icon: true` fix this?

**Comment by Alexander-Wilms** [comment]
The title bar now shows the correct icon

**Comment by grulja** [comment]
Sort of fixed, I managed to get the correct icon to the taskbar, but no idea why it doesn't work for the icon in the window decoration.

Commit: https://github.com/flathub/org.telegram.desktop/commit/09127b511be4596641f94e340eda42236650d409

**Comment by glaubersm** [comment]
upstream bug was recently fixed
https://github.com/telegramdesktop/tdesktop/issues/5180

**Comment by aleixpol** [comment]
This can be closed now. I had to fix the second part of the problem in kwin.
https://commits.kde.org/kwin/7ea7aa1ee901921ca4f15e35e07ca8247af7e95b

**Comment by gasinvein** [comment]
Thanks.
