### ISSUE TITLE
Telegram freezes while downloading files

### ISSUE THREAD

**Issue by guihkx** [flathub/org.telegram.desktop#276]
Hi.

I'm not sure what's going on, but any file I try to download makes Telegram immediately freeze and I have no choice other than terminate the process.

It's been a while since I last used Telegram, but this did not happen back in version 2.7.x.

I couldn't get any useful information as to why it freezes, though. Running Telegram on terminal gives me this:

```
(telegram-desktop:2): lib_base-WARNING **: 01:50:09.426: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
lib_base-Message: 01:50:09.427: This can be ignored by setting DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
lib_base-Message: 01:50:09.428: GTK integration can be disabled by setting DESKTOP_APP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to some features being unavailable.
Gtk-Message: 01:50:09.630: Failed to load module "canberra-gtk-module"
Gtk-Message: 01:50:09.630: Failed to load module "canberra-gtk-module"
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
```

`journalctl` shows nothing useful either. While frozen, the `telegram-desktop` process is just idling:

![image](https://user-images.githubusercontent.com/626206/124222943-1fba6600-dad9-11eb-8acb-25f0142870c1.png)

Info:

OS: Arch Linux
Flatpak 1.11.2
Telegram 2.8.4

**Comment by guihkx** [comment]
Okay, I forgot to mention on my post, but Telegram only freezes when I try to download files by right-clicking on them and going to "Save File As...". If I just click the download button, it doesn't freeze.

I tried downgrading to the previous Flathub commit and now it works fine:

```
$ flatpak remote-info --log flathub org.telegram.desktop
        ID: org.telegram.desktop
       Ref: app/org.telegram.desktop/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 78,5 MB
 Installed: 204,6 MB
   Runtime: org.freedesktop.Platform/x86_64/20.08
       Sdk: org.freedesktop.Sdk/x86_64/20.08

    Commit: 4255bff1c88e64628fe38aae9fbbf6eca0a43924939ad07e51263b782da03f2d
    Parent: 072900081db70579f370fe4c271f5ba62253dcb97411f2f3638fea05a9a1baf3
   Subject: Update tdesktop.git to 2.8.4 (eebadbc0)
      Date: 2021-07-02 00:06:36 +0000
   History: 

    Commit: 072900081db70579f370fe4c271f5ba62253dcb97411f2f3638fea05a9a1baf3
   Subject: Give access to PipeWire to be able to share screen (7945dc39)
      Date: 2021-06-27 12:59:16 +0000
```

```
$ sudo flatpak update --commit 072900081db70579f370fe4c271f5ba62253dcb97411f2f3638fea05a9a1baf3 org.telegram.desktop
```

So this is probably happening due to a change between 2.8.2 and 2.8.4.

**Comment by ShockwaveNN** [comment]
Same here, problem arise on latest updates

**Comment by archdron** [comment]
Same here. After the update to v2.8.4, the app freezes on file download and upload.

Fedora 34

**Comment by ilya-fedin** [comment]
Yeah, it's a new bug introduced in 2.8.4.
I can downgrade to 2.8.1, but that will lead to all local data cleared since tdesktop doesn't support downgrades.

**Comment by guihkx** [comment]
Yeah, I even edited my post to clarify that downgrading invalidates all your data. Let's either wait for a new release, or investigate which commit causes it.

**Comment by ShockwaveNN** [comment]
Thanks, can confirm problem is fixed with version `5a7d46d5b9e0bb73e70828e202a28be92b60f42c57ece7ec1ec992da63537eba`
