### ISSUE TITLE
Remove new filesystem host permission

### ISSUE THREAD

**Issue by matteo-gallo-bb** [flathub/org.telegram.desktop#294]
Please remove new filesystem host access to improve Flatpak sandboxing of Telegram.

As explained in Flatpak wiki (https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access): 
> As a general rule, Filesystem access should be limited as much as possible
> Using portals as an alternative to blanket filesystem access, wherever possible
In this case there is no need to have read-only access to all filesystem just to have Drag and Drop functionality. To attach files user can use the file manager portal instead.

If a user really needs Drag and Drop functionality we can suggest to add the permission host:ro for their specific use case, either with flatpak cli or with Flatseal.

**Comment by ilya-fedin** [comment]
We don't want to have bad UX by default. It's easier for advanced user to remove the permission.
