### ISSUE TITLE
Telegram won't start anymore

### ISSUE THREAD

**Issue by aleixpol** [flathub/org.telegram.desktop#295]
![Screenshot_20210817_185826](https://user-images.githubusercontent.com/1282478/129768927-bf109457-7d47-4b12-b394-828f76d74fe9.png)

**Comment by ilya-fedin** [comment]
oops

**Comment by gasinvein** [comment]
@ilya-fedin Looks like you've forgot actual runtime plugins path, `/usr/share/runtime/lib/plugins`, in 62089adaeb6f8507e6d5b3c4c37bfd6654e194ca

**Comment by ilya-fedin** [comment]
freedesktop runtime doesn't have Qt, this is not related to Qt plugins in anyway. It tries to write to ~/.TelegramDesktop.

**Comment by gasinvein** [comment]
> freedesktop runtime doesn't have Qt, this is not related to Qt plugins in anyway.

Right, I've forgot that we're on fd.o runtime now.

> It tries to write to ~/.TelegramDesktop.

Oh. Any idea why?

**Comment by ilya-fedin** [comment]
> Oh. Any idea why?

Because tdesktop uses it when sees it

**Comment by gasinvein** [comment]
Will it use it if it's present, but empty? If not, we can probably add `--nofilesystem=~/.TelegramDesktop` as a workaround.

**Comment by ilya-fedin** [comment]
> Will it use it if it's present, but empty?

No, it checks for multiple files to be present in it.

>  we can probably add `--nofilesystem=~/.TelegramDesktop` as a workaround.

And it will take priority over home:ro?

**Comment by gasinvein** [comment]
> > we can probably add `--nofilesystem=~/.TelegramDesktop` as a workaround.
> 
> And it will take priority over host:ro?

I think so, but better verify this.

**Comment by ilya-fedin** [comment]
@aleixpol can you check a build from flathub-beta when it will be ready?

**Comment by urigg** [comment]
In case this helps anyone: Workaround is to delete/rename .TelegramDesktop in the real home directory. For me, this was a leftover from a previous installation.
