### ISSUE TITLE
Allow local filesystem access

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.telegram.desktop#3]
Users can share images, music and video files using Telegram, however the current app doesn't have xdg-documents etc. permissions so it's impossible to save them to the local filesystem.

We received a [bug report from an Endless user](https://community.endlessos.com/t/send-data-via-telegram-app/4356) so people do actually want to do this.

**Comment by TingPing** [comment]
Qt5 should support the portals, so I'd rather somebody familiar with Qt look into why that isn't working?

**Comment by nedrichards** [comment]
For sure, very happy for someone to do that.

**Comment by grulja** [comment]
If telegram would be a normal application, then portals would work out of box, unfortunately telegram has some custom file dialog and doesn't seem to be using regular Qt's QFileDialog and thanks to that it doesn't use portals. I think there is even a bug report for that in upstream. I unfortunately haven't had time yet to look into this.

**Comment by nedrichards** [comment]
OK, given that @grulja could you merge #4 ? (or change it as you wish)

**Comment by grulja** [comment]
@TingPing, can we merge this change for now?

**Comment by nedrichards** [comment]
@grulja you're an admin on this repo! You get to make that choice as well ;-)

**Comment by TingPing** [comment]
It makes sense to me until changes make it upstream to use normal Qt file choosers
