### ISSUE TITLE
Telegram Desktop missing in GNOME Software

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.telegram.desktop#31]
It looks like that some update broke the AppStream file and Telegram Desktop is no longer available via GNOME Software.

**Comment by jurf** [comment]
Can confirm.

**Comment by TingPing** [comment]
Upstream never changed: https://github.com/telegramdesktop/tdesktop/blob/dev/lib/xdg/telegramdesktop.appdata.xml

**Comment by TingPing** [comment]
It is an odd id, so could be another `flatpak` or `appstream-glib` bug.

**Comment by AsciiWolf** [comment]
It looks like that this has been fixed and Telegram Desktop is now installable again using GNOME Software.
