### ISSUE TITLE
Invalid Filesystem Setting

### ISSUE THREAD

**Issue by xscd** [flathub/org.telegram.desktop#310]
```!~/.TelegramDesktop``` doesn't seem like a valid option. 

![Screenshot from 2021-09-02 12-54-35](https://user-images.githubusercontent.com/46658470/131823756-d02272ba-0663-4447-b984-b4b0a365c8de.png)

**Comment by gasinvein** [comment]
`!` at the start of filesystem entry in flatpak metadata means "not". The purpose of this option is to remove access to `~/.TelegramDesktop` (see #295).
Looks like Flatseal doesn't know how to handle built-in inverted permissions (no wonder if Telegram is the only app on Flathub that has it). Consider reporting this to Flatseal.

**Comment by xscd** [comment]
Thanks. https://github.com/tchx84/Flatseal/issues/314
