### ISSUE TITLE
Unable to mark messages as read while uploading video

### ISSUE THREAD

**Issue by eiglow** [flathub/org.telegram.desktop#311]
Originally reported [here](https://github.com/telegramdesktop/tdesktop/issues/16885), but I found that I don't encounter this issue on the official telegram.

Copy-pasted issue below:

### Steps to reproduce
1. Have a chat with unread messages
2. Start uploading a video in another chat (not Saved Messages, the issue won't occur if you upload there)
3. Switch to the chat with unread messages

### Expected behaviour
The messages should be marked as read

### Actual behaviour
The messages are not marked as read, the badge indicator on the left pane stays the same instead of clearing. Clicking the chat again will bring you to the first unread messages as if you had never clicked on it. Even if you had scrolled down from the first unread, clicking will bring you back up.

One workaround for this is to minimise and restore the window, that then clears the badge while the video is still uploading.

### Configuration
**Operating system:** Fedora 34 (KDE Spin - Wayland session)

**Version of Telegram Desktop:** 3.0.1

**Used theme**: Default night mode

Let me know if you can't reproduce and I'll try to give more detailed reproduction steps.

**Comment by ilya-fedin** [comment]
Such a bug can't be a packaging issue. I'm sure it just reproduces randomly so you weren't able to reproduce with other build.

**Comment by eiglow** [comment]
I have tried it multiple times on different machines with the official telegram and with the flatpak telegram, and I still think it's not random. Did you try to reproduce it?

**Comment by ilya-fedin** [comment]
> Did you try to reproduce it?

No, I don't want to upload a video...

> I have tried it multiple times on different machines with the official telegram and with the flatpak telegram, and I still think it's not random.

I don't believe that can happen, the code is the same if you're trying the same version numbers in both cases.
