### ISSUE TITLE
Regular crashes

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [flathub/org.telegram.desktop#315]
Hi!

I am facing regular crashes (several times per hour) in `telegram-desktop` from Flathub.

In `dmesg -T` I see something like this one:
```
[Вс сен 12 14:09:31 2021] traps: telegram-deskto[2244654] general protection fault ip:7f12bd469011 sp:7fffa91b73e0 error:0 in libQt5Widgets.so.5.15.2[7f12bd200000+3c9000]
[Вс сен 12 14:25:26 2021] telegram-deskto[2542098]: segfault at 0 ip 0000561102906599 sp 00007fffd0991da0 error 4 in telegram-desktop[5611007cd000+21aa000]
[Вс сен 12 14:25:26 2021] Code: 4c 8d 7d 30 81 e3 f0 00 00 00 48 01 eb 48 8b 53 30 49 39 d6 0f 85 df 01 00 00 4c 89 e0 48 c1 e8 09 25 f8 ff 1f 00 48 03 43 38 <48> 8b 10 4c 8d 05 9d 37 d8 01 48 89 d0 48 c1 e8 30 89 c1 49 8b 34
```
Even if I am not touching telegram, it crashes. The crash appears more frequently if I am switching between chats.

Is there any way/workaround for fixing this?

Additional information:
OS: Fedora 34
flatpak --version: 1.10.2
Telegram-desktop (org.telegram.desktop) version: 3.0.1

Thanks in advance!

**Comment by gasinvein** [comment]
It crashed for me several times since ~3.0, but certainly not that frequent.
Providing a backtrace may be helpful. To do that, you'll need to install `org.telegram.desktop.Debug` and run `flatpak-coredumpctl org.telegram.desktop` to get into GDB shell, then run `bt` to get the backtace from latest crash.

**Comment by ZaMaZaN4iK** [comment]
https://pastebin.com/7qwg4Ezk

Here it is. If you need any additional info - ping me. I'll try to help.

**Comment by ilya-fedin** [comment]
Can you check whether you have crashes on 3.0.3? (it's in flathub-beta)

**Comment by ZaMaZaN4iK** [comment]
Sure. I've just installed the latest Telegram Desktop version from flathub-beta and will test for some time (I think several days or smth like that). Then I'll inform you about the results.

Thanks!

**Comment by ZaMaZaN4iK** [comment]
@ilya-fedin I was testing suggested by you Telegram version extensively all the time from yesterday and see no crashes. So I think the issue can be resolved by upgrading Telegram version to 3.0.3 in stable flathub repo.

Please close the issue, when the fresh version of Telegram will be published to flathub stable. Thanks!

**Comment by ilya-fedin** [comment]
3.0.3 is a beta version, so it can't be pushed to stable repo

**Comment by ZaMaZaN4iK** [comment]
I hope it's in beta state only for now. Am I right that in near it will be stabilized and then marked as "stable"?

**Comment by ilya-fedin** [comment]
No, upstream needs to release a stable version.

**Comment by ZaMaZaN4iK** [comment]
Okay. So we will wait for the next stable version.

**Comment by Qwertie-** [comment]
Can also reproduce this issue. Happens very frequently (every few minutes) and especially when clicking a different chat.
