### ISSUE TITLE
Recent Change in Notifications: No way to disable Native notifications

### ISSUE THREAD

**Issue by motoridersd** [flathub/org.telegram.desktop#328]
At some point in the last few releases, the option to use Telegram's own notifications disappeared. It now uses GNOME Native Notifications by default. Unfortunately, native GNOME message notifications don't work as expected. Clicking on a new message pop up will close the Telegram window instead of taking me to it. 

The Linux BInary from the tdesktop github has the original Telegram notifications still available.

The options below are gone from the current flatpak version:

![image](https://user-images.githubusercontent.com/5197858/135100282-d641cc58-cc68-4e94-9800-b24fc62528ee.png)

**Comment by ilya-fedin** [comment]
What version are you using? Can you show the result of `env | grep QT`?

**Comment by motoridersd** [comment]
Telegram Desktop client 3.1.1

```
env | grep QT
QT_IM_MODULE=ibus
```
I *am* running the flatpak client in forced Wayland mode. I have a bug where the window isn't moveable on first launch, and Wayland mode fixes it. I just realized that if I don't force Wayland (--env=QT_QPA_PLATFORM=wayland) the notifications options are there.

**Comment by ilya-fedin** [comment]
Wayland protocol doesn't provide enough API to implement custom notifications, there's nothing can be done
