### ISSUE TITLE
Can't open links

### ISSUE THREAD

**Issue by lightonflux** [flathub/org.telegram.desktop#33]
Debian Testing:

When running this flatpak and clicking on links (http, https) nothing happens. The links are not opened in a browser. 

Is this portal active? [link](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.OpenURI)

**Comment by jurf** [comment]
I use this on a daily basis, hadn’t yet had a problem (just tried it). It used to do it but that was long fixed and IIRC a problem on the portal side. What flaptak/portal versions do you have?

**Comment by ar-nelson** [comment]
I have the same problem. Arch Linux, flatpak 1.0.1-1 installed through `pacman`. Clicking a link doesn't open in a browser, and it also freezes Telegram.

I use a WM without a DE (fluxbox), but `xdg-open` is configured to open links in Firefox.

**Comment by ar-nelson** [comment]
`gio open http://example.com` opens Firefox, and `xdg-desktop-portal-gtk` is installed, but the problem still exists. :/

**Comment by grulja** [comment]
Is this still reproducible?

**Comment by lightonflux** [comment]
Works for me with the most recent Debian Testing and Flatpak.
@ar-nelson can you reproduce it at this point in time.
