### ISSUE TITLE
Missing Notification Icon - Ubuntu Mate 20.04

### ISSUE THREAD

**Issue by greensysadmin** [flathub/org.telegram.desktop#345]
![indicatorapplet](https://user-images.githubusercontent.com/94113459/141289161-df73ccc8-86ce-45e8-9e70-5e10dbc135ae.png)

## Expected Behaviour

Telegram loads a notification icon in the Mate Indicator Applet, with a notification badge for new messages

## Actual Behaviour

Telegram loads with a black box with a stop sign inside of it, instead of the correct icon and there is no notification badge (see attached screenshot)

## Steps to Reproduce the Problem

  1. Install latest version of Telegram Flatpak from Flathub
  2. Open Telegram Flatpak
  3. Observe missing icon

## Specifications

  - Version: 3.2.3
  - Platform: Ubuntu MATE 20.04.3 LTS with default Ambient MATE theme (but happens on other tested themes)

This only started happening with a recent update. I tested the standalone binary Telegram provide, as well as the Snap, of 3.2.3 and the notification icon appears as expected.

Output of `flatpak run org.telegram.desktop` in a terminal:

```
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
Gtk-Message: 11:19:55.134: Failed to load module "appmenu-gtk-module"
Gtk-Message: 11:19:55.134: Failed to load module "canberra-gtk-module"
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
```

**Comment by ilya-fedin** [comment]
:thinking: I can't reproduce anything like this on NixOS with MATE

**Comment by greensysadmin** [comment]
Just did a quick test on a few live boots on KVM:

Ubuntu MATE 21.10 - Issue is present
Fedora 35 MATE - Works fine
Debian 11 Buster MATE - Works fine

(Wanted to try Solus but their current live boot image for MATE is broken :-()

So looks to be an Ubuntu specific issue - Ubuntu MATE 21.10 and Debian both output:

```
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
```
But the icon appears correctly in Debian but not Ubuntu.

Fedora outputs:

`[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)`

And the icon appears correctly.

**Comment by ilya-fedin** [comment]
I defintely won't install Ubuntu to check this, sorry :(

**Comment by ilya-fedin** [comment]
> QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700

it's flatpak/bubblewrap who sets the permission, so maybe you have an old flatpak version, try to update it to the latest version

**Comment by greensysadmin** [comment]
> > QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
> 
> it's flatpak/bubblewrap who sets the permission, so maybe you have an old flatpak version, try to update it to the latest version

Yup, this seems to have fixed it - I installed Flatpak 1.11.2 from Alex's PPA:

https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

And the issue is resolved.

**Comment by greensysadmin** [comment]
Ah, I've been informed the correct PPA is now actually:

https://launchpad.net/~flatpak/+archive/ubuntu/stable

**Comment by thalesmaoa** [comment]
I confirm that issue emerged after upgrade.

```
$  cat /etc/os-release
NAME="elementary OS"
VERSION="6 Odin"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6 Odin"
LOGO=distributor-logo
VERSION_ID="6"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=odin
UBUNTU_CODENAME=focal
```

Even using Alex's PPA, I can't upgrade to test it:
```
$ flatpak --version
Flatpak 1.10.2
```

**Comment by greensysadmin** [comment]
Sorry, Alex's PPA is no longer current. This is the correct one:

https://launchpad.net/~flatpak/+archive/ubuntu/stable

I have amended my above posts to reflect this.
