### ISSUE TITLE
HiDPI scaling issue with GNOME+Wayland starting from 3.4

### ISSUE THREAD

**Issue by pabl0** [flathub/org.telegram.desktop#360]
After upgrading to 3.4, all UI elements are tiny on GNOME+Wayland with 4K monitor (Debian 10).  There are very thick black borders around the app window that did not exists there before (3.3). 

I am able to change the scaling settings to 150% which fixes the scaling issue somewhat, but it seems everything renders bit weirdly (sometimes menu items are drawn only when you hover the cursor over). Furthermore, I cannot resize the window at all.

This is a clear regression from the previous version where the UI worked perfectly on this setup.

**Comment by ilya-fedin** [comment]
Only packaging issues are accepted here
