### ISSUE TITLE
telegram app is blurry with experimental fractional scaling feature enabled since version 3.4.3

### ISSUE THREAD

**Issue by alex0z1** [flathub/org.telegram.desktop#365]
I have hidpi scaling (enabled by `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`, with scale set to 150%) on Fedora 35/Gnome 41.2. To fix blurry telegram app UI I used `flatpak override --env=QT_QPA_PLATFORM=wayland org.telegram.desktop`. This "fix" does not work since most recent update to `3.4.3` (45deeb86). Rolling back  to previous version (`3.4.2` (e9adad97)) using `fatpak update --commit=45977570427e792ae027fad41f5a072628140fc5cc2d06099acfd6c638b62ec8  org.telegram.desktop && flatpak mask org.telegram.desktop`  fixes the issue

**Comment by q234rty** [comment]
Native wayland on GNOME was intentionally disabled due to bad experience under older versions of Mutter.
Consider `flatpak override --env=XDG_CURRENT_DESKTOP=XFCE org.telegram.desktop` as a workaround.

**Comment by alex0z1** [comment]
@q234rty thank you, your workaround worked as expected
