### ISSUE TITLE
Allow to run multiple instances at the same time

### ISSUE THREAD

**Issue by abyss7** [flathub/org.telegram.desktop#37]
Telegram client allows to run multiple accounts at once with options `-many` and `-workdir`. How to make it possible to setup and run different accounts using flatpak?

**Comment by TingPing** [comment]
`flatpak run org.telegram.desktop -many` probably.

**Comment by fkoester** [comment]
I also had some trouble getting it to work but after some fiddling I found a solution:

1. Create the desired workdirs for the telegram instances, for instance:

    ```sh
    mkdir ~/.var/app/org.telegram.desktop/data/TelegramDesktopBiz
    mkdir ~/.var/app/org.telegram.desktop/data/TelegramDesktopPrivate
    ```
2. Then you can execute two independent instances with the following commands:
    ```sh
    flatpak run org.telegram.desktop -many -workdir .var/app/org.telegram.desktop/data/TelegramDesktopBiz
    flatpak run org.telegram.desktop -many -workdir .var/app/org.telegram.desktop/data/TelegramDesktopPrivate
    ```

Hope this helps!

**Comment by gasinvein** [comment]
I believe this is resolved somehow. Also Telegram is going to support multi-account since 2.1.14.
