### ISSUE TITLE
Tray icon is missing in KDE Plasma 5 (Xorg)

### ISSUE THREAD

**Issue by abyss7** [flathub/org.telegram.desktop#38]
`Show tray icon` option is set, but an icon doesn't appear in the tray. The non-flatpak installation of Telegram shows icon well.

**Comment by baumkuchen42** [comment]
I don't see the option (under Gnome) and I'd really like to disable it because it caused problems with the non-flatpak version of Telegram. As the flatpak version is quite buggy on my system I guessed that this could be the root of the problem.

**Comment by grulja** [comment]
Hi @baumkuchen42, Is the original issue stil reproducible?

**Comment by baumkuchen42** [comment]
@grulja I haven't experienced the performance issues I had back then when I filed the bug report. It seems to be fixed, or it wasn't a problem of Telegram but of my system itself.

**Comment by LeonardKoenig** [comment]
At least I still need to run telegram like this:
```
$ flatpak run --own-name='org.kde.*' org.telegram.desktop
```
Otherwise I get `failed to register service "org.kde.StatusNotifierItem-2-1"` -- so this should probably be added to the owns in the json.
