### ISSUE TITLE
New Upstream Release 1.4.3

### ISSUE THREAD

**Issue by Tids** [flathub/org.telegram.desktop#41]
https://github.com/telegramdesktop/tdesktop/tree/v1.4.0 was released a few hours ago.
I however don't know if the patches are still compatible 😅

**Comment by Tids** [comment]
sadly I'm unable to build it myself. range3 is already to heavy for my hardware. 😔

**Comment by grulja** [comment]
Here https://github.com/flathub/org.telegram.desktop/commit/09768a28728970ac9d8797252fcea27944d2366a is my attempt to update telegram to version 1.4.0. This doesn't build unfortunately, but that's typical for Telegram. I'll look into this once I have some free time or if anyone wants to look into it, feel free to do so.

**Comment by Tids** [comment]
https://github.com/telegramdesktop/tdesktop/tree/v1.4.3 is out by now.
Also Arch made it run and I think they are using the same patches as flathub does
https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/telegram-desktop

**Comment by grulja** [comment]
Updated now, build should be in progress.

**Comment by jurf** [comment]
Thanks!
