### ISSUE TITLE
Rebuild with org.kde.platform/5.11

### ISSUE THREAD

**Issue by trochdewei** [flathub/org.telegram.desktop#42]
Could you please rebuild telegram with new KDE runtime?

**Comment by grulja** [comment]
Is there any reason why to use KDE runtime 5.11?

**Comment by grulja** [comment]
There will be KDE runtime 5.12 in a month, once Qt 5.12 LTS is released and it's going to be based on the new freedesktop runtime. Once it's released I will update telegram to use it.

**Comment by grulja** [comment]
Telegram now uses Qt 5.12.
