### ISSUE TITLE
Where permissions come from?

### ISSUE THREAD

**Issue by gasinvein** [flathub/org.telegram.desktop#44]
Today I've updated Telegram and got this permissions:
```
org.telegram.desktop/x86_64/stable flathub 8fdb9e278b59
  permissions: ipc, network, pulseaudio, wayland, x11, dri
  file access: xdg-config/kdeglobals:ro, xdg-documents, xdg-download, xdg-music, xdg-pictures, xdg-run/dconf, xdg-videos, ~/.config/dconf:ro
  dbus access: com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*, org.freedesktop.Notifications, org.kde.StatusNotifierWatcher
```
But `com.canonical.AppMenu`, `xdg-config/kdeglobals:ro`, `~/.config/dconf:ro` and maybe some others are not present in manifest:
https://github.com/flathub/org.telegram.desktop/blob/cfb1722996abf08049aed5d89264f924d57113f5/org.telegram.desktop.json#L13-L25
Where did they come from?

**Comment by TingPing** [comment]
https://github.com/KDE/flatpak-kde-runtime/blob/master/org.kde.Sdk.json#L56

**Comment by gasinvein** [comment]
And why they are not present in otrher Qt apps, e.g. qBittorrent?

**Comment by TingPing** [comment]
There was a period where `flatpak` stopped inheriting these permissions and it was recently readded. So maybe just timing of their last build but not certain.

**Comment by gasinvein** [comment]
Can I do this locally? My local builds (flatpak-builder 1.0) of apps don't seem to inherit permissions from runtimes.

**Comment by grulja** [comment]
You need flatpak 1.0.4 for apps to again pick permissions from the runtime.
