### ISSUE TITLE
Missing icons in file chooser

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.telegram.desktop#5]
It looks like we're not bundling the icons required for the file chooser, as you can see in the screenshot there's a lot of 'missing icon' icons.

![screenshot from 2017-10-10 16-01-00](https://user-images.githubusercontent.com/302677/31393715-4a37a450-add4-11e7-92e6-273630909de5.png)

**Comment by TingPing** [comment]
Very recent `flatpak` will actually use host icons now. Can package the default one but this issue is also avoided when the portals work as mentioned in #3

**Comment by nedrichards** [comment]
Ah cool, I'm on 0.9.8 so happy to close.

**Comment by TingPing** [comment]
For future reference 0.9.11 includes the icon change.
