### ISSUE TITLE
Set TMPDIR=/var/tmp instead of using a wrapper script

### ISSUE THREAD

**Issue by jurf** [flathub/org.telegram.desktop#57]
Unless external programs somehow check if the Flatpak’d Telegram is running, setting `--env=TMPDIR=/var/tmp` should be enough (and is much cleaner than creating a wrapper script).

http://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

**Comment by grulja** [comment]
We use this to avoid running multiple instances. If one Telegram instance is running and hidden in tray and you open it again through a launcher, without this it would start one more instance.

**Comment by jurf** [comment]
Yeah, I know, see https://github.com/flathub/org.musescore.MuseScore/commit/832769b79c12ee3893cef1e2fae9cac7a310e742

**Comment by grulja** [comment]
I assumed /var/tmp will not be seen by other telegram instances. I can try it and do it this way if it works.

**Comment by jurf** [comment]
It will be actually.

**Comment by TingPing** [comment]
`/var/tmp` is equal to `$XDG_CACHE_HOME/tmp` so it is visible to to all instances.

**Comment by jurf** [comment]
@TingPing is that so? Why would one want to create a wrapper script then?

**Comment by TingPing** [comment]
> Why would one want to create a wrapper script then?

If the path is passed outside of the sandbox, for example to an appindicator tray, `/var/tmp` will be a nonsense path there.
