### ISSUE TITLE
Opening the application twice opens 2 applications

### ISSUE THREAD

**Issue by aleixpol** [flathub/org.telegram.desktop#6]
The mechanism Telegram Desktop has to make sure it's running just once is bypassed by the container, so every time it's started it spawns a new process.

Possibly should be changed upstream to use dbus. Or something entirely different.

**Comment by grulja** [comment]
Telegram used to have --filesystem=/tmp in its manifest to support that, but that didn't pass the review process. If I find some time I can look into making this work through dbus or something else.

**Comment by TingPing** [comment]
Well even in the short term it should just respect `$TMPDIR` upstream if it doesn't...

**Comment by grulja** [comment]
I just realized that we discussed this and workarounded it by setting $TMPDIR env to $XDG_CACHE_HOME, obviously this is not enough.

**Comment by aleixpol** [comment]
This issue isn't fixed here, please reopen (or fix :)).
