### ISSUE TITLE
Missing font for Japanese symbols in flatpaked Telegram Desktop

### ISSUE THREAD

**Issue by nexfwall** [flathub/org.telegram.desktop#63]
![Screenshot](https://user-images.githubusercontent.com/8678891/51800045-e95acb80-223a-11e9-92dc-aeeab300d546.png)
But there should be " エージェントの邪悪な笑い ".

**Comment by noangel** [comment]
+1 same here, also Korean symbols displayed as boxes.

**Comment by kenya888** [comment]
Here's a work-around in my environment.

We can change the font settings of tdesktop via fontconfig (the Qt way)
tdesktop app has custom fontconfig settings as following.

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L49

In flatpak environment, you can find this file at

~/.var/app/org.telegram.desktop/data/TelegramDesktop/tdata/fc-custom-1.conf

There are two points to check for modification.

1. add '/run/host/fonts' to <dir> directive.
2. set the font that you want to use.

Here is my sample (Noto CJK JP)

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
        <dir>/usr/share/fonts</dir>
        <dir>/usr/local/share/fonts</dir>
        <dir>~/.fonts</dir>
        <dir>~/.local/share/fonts</dir>
        <dir>/run/host/fonts</dir>
        <dir>/usr/X11R6/lib/X11/fonts</dir>
        <dir prefix="xdg">fonts</dir>
        <match target="pattern">
                <test qual="any" name="family">
                        <string>mono</string>
                </test>
                <edit name="family" mode="assign" binding="same">
                        <string>Noto Mono</string>
                </edit>
        </match>
        <match target="pattern">
                <test qual="any" name="family">
                        <string>sans serif</string>
                </test>
                <edit name="family" mode="assign" binding="same">
                        <string>Noto Sans CJK JP</string>
                </edit>
        </match>
        <match target="pattern">
                <test qual="any" name="family">
                        <string>sans</string>
                </test>
                <edit name="family" mode="assign" binding="same">
                        <string>Noto Serif CJK JP</string>
                </edit>
        </match>
        <cachedir>/var/cache/fontconfig_11</cachedir>
        <cachedir prefix="xdg">fontconfig_11</cachedir>
        <cachedir>~/.fontconfig_11</cachedir>
        <match target="font">
        <edit mode="assign" name="antialias">
                <bool>true</bool>
        </edit>
        <edit mode="assign" name="embeddedbitmap">
                <bool>false</bool>
        </edit>
        <edit mode="assign" name="hinting">
                <bool>true</bool>
        </edit>
        <edit mode="assign" name="hintstyle">
                <const>hintslight</const>
        </edit>
        <edit mode="assign" name="lcdfilter">
                <const>lcddefault</const>
        </edit>
        <edit mode="assign" name="rgba">
                <const>rgb</const>
        </edit>
        </match>
</fontconfig>
```

![tdesktop_flatpak_cjkfont](https://user-images.githubusercontent.com/1095169/52517426-8cb9d080-2c7e-11e9-82aa-632124030421.png)

**Comment by noangel** [comment]
@kenya888 ありがとうございます。ちゃんと日本語が表示されました！

Worked for me!

**Comment by simontol** [comment]
Reference : https://github.com/flathub/com.slack.Slack/issues/14
My comment: https://github.com/flathub/com.slack.Slack/issues/14#issuecomment-471171694

**Comment by simontol** [comment]
@kenya888 
Adding `<dir>/run/host/fonts</dir>` is enough for me. Thanks

**Comment by nate2014jatc** [comment]
+1 for Chinese Chars, testing the workaround now

**Comment by ahayzen** [comment]
Note for anyone experiencing this issue, if you have been running telegram before the patch was applied, you will need to run `sudo rm ~/.var/app/org.telegram.desktop/data/TelegramDesktop/tdata/fc-custom-1.conf` to clear the old fontconfig file. Then when you run the patched version of telegram it will install a new fontconfig that includes `/run/host/fonts`.

**Comment by eternal-sorrow** [comment]
I have the `<dir>/usr/share/fonts</dir>` line in the` fc-custom-1.conf` file, but still have this issue. What's wrong?
![2021-03-13-092722](https://user-images.githubusercontent.com/4847726/111009192-d78d0180-838a-11eb-8bfe-8f2264e1cd96.png)

**Comment by ilya-fedin** [comment]
tdesktop doesn't use fc-custom for a very long time. tdesktop should use the same configs other Qt applications are using.

**Comment by eternal-sorrow** [comment]
So? How do I fix this?

**Comment by ilya-fedin** [comment]
I have no idea. AFAIK It should work automatically if your fonts are in directories that flatpak can read.

**Comment by eternal-sorrow** [comment]
Just tried, CJK symbols display correctly in GTK apps both flatpak instaled and native, but do not display in Qt apps, installed with flatpak. I did not test in native Qt apps because I don't have them installed. What can I do in this case.

**Comment by ilya-fedin** [comment]
Probably report to Qt or to flathub KDE runtime maintainers?
