### ISSUE TITLE
Problems with the tray icon. Gnome

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.telegram.desktop#65]
In Ubuntu 18.04, Gnome Shell with the extension "Topicon plus" the icon disappears when the screen goes down. (also happens to qbittorrent)

With the native extension of Ubuntu "Ubuntu appindicators" the icon remains well.

**Comment by andrew-vimmer** [comment]
Same here, on Fedora 28.
```
gnome-shell.x86_64                         3.28.3-1.fc28
gnome-shell-extension-topicons-plus.noarch 21-7.20181024.6470a38.fc28

org.telegram.desktop/x86_64/stable flathub 2e60a5ce3ecd
```

The icon disappears after a screen lock.

**Comment by AsciiWolf** [comment]
Yeah, I have the same issue with latest TopIcons Plus on Fedora 29.

**Comment by giuseppe1993** [comment]
I also have the same problem with the latest TopIcons Plus on Fedora 30

**Comment by grulja** [comment]
Most likely fixed with https://github.com/flathub/org.telegram.desktop/pull/74. For now it's only in `beta` branch as it depends on unreleased version.

**Comment by pgera** [comment]
The tray icon broke for unity as well recently. It used to work fine until a couple of releases ago.

**Comment by dinozof** [comment]
broken for me as weel on Gnome 3.28.2

**Comment by Tids** [comment]
Since gnome does not support tray icons any longer, this shouldn't be a bug - but an expected behavior at some point. Also Telegram works pretty good without tray support.

**Comment by pgera** [comment]
Well, other DEs like unity still support tray icons and functionality. This looks like a regression since it was working until about a month ago.

**Comment by gasinvein** [comment]
Does it work for you with appindicator-support extension?

**Comment by Tids** [comment]
> Well, other DEs 

Gnome is Gnome. Not other DE. You really can not compare one project to another. They have different goals. It's not a bug on Gnome if it works for others, while Gnome clearly stated that there is no support for it.

> like unity

Lomiri? 

> still support tray icons and functionality. 

Like said earlier. Whats the relation between this and Gnome?

> This looks like a regression since it was working until about a month ago.

That's how unsupported things will end, always: https://en.wikipedia.org/wiki/Software_rot

------------------- 
It might be a change, but you can enable native notifications in telegram and use the gnome notification center to track new messages. It's simple, supported and out-of-the-way.

**Comment by pgera** [comment]
Not lomiri, unity 7 (the one that used to ship with 16.04). I'm not sure if you are trying to say that this flatpak (or flatpaks in general) are not supported on DEs other than gnome, or that I should file a separate issue instead of the one about gnome. If it is the latter, yeah, I can do that. Would be quite redundant though.

**Comment by alexb3d** [comment]
> It might be a change, but you can enable native notifications in telegram and use the gnome notification center to track new messages. It's simple, supported and out-of-the-way.

Actually, it is a problem, because to receive notifications you have to have the application open for each program you use. That is a consumption of resources.

**Comment by Tids** [comment]
> Actually, it is a problem, because to receive notifications you have to have the application open for each program you use.

You do anyway. Telegram does not have any kind of background service. It just hides its window.

> That is a consumption of resources.

Resource usage is the same in any way.

If you dont like this, maybe open a report so that telegram can support to actually run in the background. There is also a [xdg desktop portal](https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.impl.portal.Background.xml) for this, might be of no use here, but there it is.

**Comment by alexb3d** [comment]
> You do anyway. Telegram does not have any kind of background service. It just hides its window.

This is false, when you close the window stop working any application that uses tray icon. Telegram, Qbittorrent, Mega, Dropbox, Twitch, ETC... The only one that still works is Geary. I use Ubuntu LTS 18.04. Check the information before commenting.

> Resource usage is the same in any way.

This is false! Shell uses hardware acceleration, if you have the windows open, every time you use the expose, you have to draw them in memory and that is use of CPU, RAM, GPU, vRAM. Check the information before commenting.

> If you dont like this, maybe open a report so that telegram can support to actually run in the background. There is also a xdg desktop portal for this, might be of no use here, but there it is.

I'm sorry, no, it's time for GNOME to do the job, that's why they're charging very well.

**Comment by gasinvein** [comment]
Please check if the issue is still present with 1.9.21

**Comment by pgera** [comment]
The missing tray icon on unity 7 is resolved after the latest update.

**Comment by ilya-fedin** [comment]
> Check the information before commenting.

You say it in every message, but don't do it yourself

> It just hides its window.

That's true.

> If you dont like this, maybe open a report so that telegram can support to actually run in the background.

Telegram will request this permission when you try to enable the autostart checkbox

So, if there are tray and the permission is given, Telegram will work in background

**Comment by alexb3d** [comment]
> Telegram will request this permission when you try to enable the autostart checkbox
> 
> So, if there are tray and the permission is given, Telegram will work in the background

This doesn't sound like a serious GitHub conversation.

I am using Ubuntu 20.04 LTS with Flatpak.

The first time the app is opened it asks for permissions, but it doesn't stay in the background. Closing the window closes the application completely.

IT DOES NOT WORK.

Please check the information before posting.

**Comment by ilya-fedin** [comment]
> IT DOES NOT WORK.
> 
> Please check the information before posting.

Typical gnomer)))

> The first time the app is opened it asks for permissions, but it doesn't stay in the background.

I don't know what it asks for you on opening, but in the code it asks only when you try to enable autostart. I know because I implemented this :_

**Comment by alexb3d** [comment]
> Gnómero típico)))

Gnomers is your mother's bitch. I use Windows.
You can go wash your ass.

**Comment by alexb3d** [comment]
> Tray is required.


That shit doesn't work in the background.
I have to have it open.
Open windows consume more resources.
Damn ignorant.

Do I still have to use an extension that doesn't work?
You have to be a damn gay millenians.

**Comment by ilya-fedin** [comment]
Ok, it's better to leave you with your own
