### ISSUE TITLE
Loosing host GTK theme under Wayland

### ISSUE THREAD

**Issue by danields761** [flathub/org.telegram.desktop#68]
Hi,

I noticed, when Telegram application is run under Wayland (using QT_QPA_PLATFORM=wayland) it looses host OS GTK theme:

Just compare:

* Using Wayland
![under_wayland](https://user-images.githubusercontent.com/13323567/56461200-679cb900-63b7-11e9-90bc-424aaca8cab7.png)

* Using xWayland
![undex_xwayland](https://user-images.githubusercontent.com/13323567/56461201-68354f80-63b7-11e9-9271-c9ac29924916.png)

**Comment by TingPing** [comment]
This is probably a discussion for Qt (or the GNOME platform for Qt).

**Comment by grulja** [comment]
What do you mean with GTK theme? Do you mean the window decoration? Otherwise Telegram uses heavily customized UI so no theme is actually applied.

**Comment by danields761** [comment]
@TingPing, sounds truly, thx
I will try to run telegram compiled from sources, it will help to localize source of problem exactly

@grulja, i mean window decorations. As you can see on my samples, they are different

**Comment by grulja** [comment]
There is unfortunately no Gnome/Gtk platform integration involved in this case, it's Qt's wayland platform plugin with wrong decoration. I have long-term plan to improve this situation, but didn't have time yet to look into this. 

So it's not a valid bug for Telegram and not Flatpak related at all.

**Comment by espectalll** [comment]
Hey, I had this issue and I was able to patch it by changing the xcb plugin so the titlebar is drawn by Xwayland, with the following variable:

`QT_QPA_PLATFORM=xcb`

You can modify the .desktop shortcut, use an environment script, or a `~/.config/environment.d ` file to get this to work permanently

**Comment by Bryophyllum** [comment]
I'm seeing this issue on the 2.14. Downgrading to the 2.10 serves as a temporary workaround. 

`$ QT_DEBUG_PLUGINS=1 flatpak run --env=QT_QPA_PLATFORM=wayland org.telegram.desktop`:
https://gist.github.com/Bryophyllum/16321b16ac67b30459324692688d8311

`$ flatpak list` (the list has been intentionally truncated):
```
Name                                                 Application ID                                                   Version                Branch             Installation
Adwaita dark GTK theme                               org.gtk.Gtk3theme.Adwaita-dark                                                          3.22               system
Adwaita theme                                        org.kde.KStyle.Adwaita                                                                  5.14               system
KDE Application Platform                             org.kde.Platform                                                                        5.14               system
QGnomePlatform                                       org.kde.PlatformTheme.QGnomePlatform                                                    5.14               system
QGnomePlatform-decoration                            org.kde.WaylandDecoration.QGnomePlatform-decoration                                     5.14               system
Krita                                                org.kde.krita                                                    4.2.9.0                stable             system
Firefox                                              org.mozilla.firefox                                              76.0.1                 stable             system
PulseAudio Volume Control                            org.pulseaudio.pavucontrol                                       4.0                    stable             system
Telegram Desktop                                     org.telegram.desktop                                             2.1.4                  stable             system
```



![Screenshot from 2020-05-10 14-52-50](https://user-images.githubusercontent.com/27376783/81499843-993c3700-92ce-11ea-95c7-ccaeb3278274.png)

**Comment by ilya-fedin** [comment]
Do you mean Telegram's new decorations by losting GTK theme?

**Comment by Bryophyllum** [comment]
@ilya-fedin That's correct. Was that a deliberate alteration to decorations?

A screenshot of the old decorations for comparison: 
![Screenshot from 2020-02-01 14-51-15](https://user-images.githubusercontent.com/27376783/73593257-56fe9f00-4502-11ea-9f94-f199ba71d533.png)

**Comment by ilya-fedin** [comment]
> Was there a deliberate alteration to decorations?

Yes
