### ISSUE TITLE
App icon not showing badges

### ISSUE THREAD

**Issue by uncertainquark** [flathub/org.telegram.desktop#69]
Telegram shows badges for new messages (supported by Ubuntu, elementary OS, KDE, etc.). Their binary file as well as the Snap version do so. However, the Flatpak app from Flathub doesn't show badges.

**Comment by grulja** [comment]
What are those? Do you mean the counter of unread messages?

**Comment by uncertainquark** [comment]
Yes. It is displayed on the Telegram icon for the Telegram binary and Snap. You can see it in action on Ubuntu snap app on the app launcher/dock to the left.

**Comment by grulja** [comment]
It works for me, I tested it now and I could see a red circle with a number of unread messages.

**Comment by uncertainquark** [comment]
Oh. :/
Could you please share a screenshot with me? And if possible details of your OS. I'm on Ubuntu 19.04 and have tested the same on 18.04 LTS and elementary OS Juno before this.

**Comment by grulja** [comment]
See https://jgrulich.fedorapeople.org/telegram.png. I'm running Fedora 30 with Plasma 5.15.4.

**Comment by uncertainquark** [comment]
Oh no, this is the badge on the indicator icon. I'm talking about the app icon on the taskbar.

**Comment by uncertainquark** [comment]
Hi, here's an example of the main app icon in the task bar/dock supporting badges/counter for new messages. This one's the Snap package of Telegram, it works on the official binary as well.

![Screenshot from 2019-05-05 13-08-59](https://user-images.githubusercontent.com/22585732/57220709-03663000-701a-11e9-8f63-45a28a808678.png)

Sorry, I should've shown it before to avoid confusion.

**Comment by grulja** [comment]
Should be fixed now.
