### ISSUE TITLE
Can't save a video on my file system

### ISSUE THREAD

**Issue by aleixpol** [flathub/org.telegram.desktop#8]
It keeps saving it within the container and I can't access it. 😢

**Comment by TingPing** [comment]
Where are you trying to save it? The application has write access to your videos directory for example.

**Comment by aleixpol** [comment]
I did on the default directory. Then I went up to the home directory which was obviously wrong too.

**Comment by TingPing** [comment]
It does not currently grant access to home. Discussed a bit in #3

**Comment by aleixpol** [comment]
Well that's beyond the point. The UX should make sense.
It's barely acceptable that I save a file to use with another piece of software and I can't.

How is the user supposed to know where the videos can go? Or any document for that matter.

**Comment by TingPing** [comment]
Well as the linked issue points out, it is a "bug" that the file chooser doesn't work as expected.
