### ISSUE TITLE
Input method fctix5 support

### ISSUE THREAD

**Issue by a-wing** [flathub/org.telegram.desktop#80]
I use fcitx5

But unable to use input method on `org.telegram.desktop`

Maybe need `fcitx5-qt`?

**Comment by ilya-fedin** [comment]
It's added in v2.1.5, please recheck after updating the package

**Comment by gasinvein** [comment]
Is the issue still present?

**Comment by ilya-fedin** [comment]
Looks like reporter no longer interested in the issue
