### ISSUE TITLE
Opening file browser freezes Telegram

### ISSUE THREAD

**Issue by mrjpaxton** [flathub/org.telegram.desktop#81]
Hello,

When I use the Flatpak version of Telegram, and I do an operation that opens up the file browser, such as sending an attachment to my post (clicking the paperclip icon on the left side of the text entry field), or changing my PFP (profile picture), it will cause Telegram to freeze.

I do not know how to turn on higher verbosity, but there are no debug/error messages that show up when I run this version of Telegram in the terminal.

The script that I use to run Telegram is this...

**Filename:** telegram.pf.sh
```
#!/bin/sh

flatpak run org.telegram.desktop "$@"
```

Sidenote: The Debian Unstable and Experimental versions of Telegram are outdated in the repos as of 27 Jul 2019, and those versions do not support animated stickers, for example. Still waiting for the maintainer to update it, so that's why I was using the Flatpak version in the meantime. I will mention that the version supplied by my distro works with the file browser well enough, but the file browser opens as a background window, instead of the foreground. I have to "Alt-Tab" into that window to select a file.

**Buggy behavior:** Telegram freezes, the file browser does not show up, and the application will not receive any more input. The application can still be closed with an external signal such as SIGTERM or SIGKILL.

**Expected behavior:** The file browser dialog opens, allows me pick a file, and Telegram continues to operate normally with the selected file. Perhaps permissions can be restricted/allowed with the `--filesystem=dir` parameter.

Oh, I tried to use `--filesystem=home` and `--filesystem=host`, and both of those didn't help resolve the problem.

Any help would be great. If you need more info, please let me know!

**Version Info:**
- Telegram Desktop 1.7.14
- Flatpak 1.4.2
- OS: Debian Unstable (Codename Sid)
- uname: Linux pc-main 5.0.0-trunk-amd64 #1 SMP Debian 5.0.2-1~exp1 (2019-03-18) x86_64 GNU/Linux

**Comment by grulja** [comment]
Do you use Gnome or KDE Plasma? What is your version of xdg-desktop-portal-gtk (if you use Gnome) or xdg-desktop-portal-kde (if you use KDE Plasma)? And your version of xdg-desktop-portal?

**Comment by mrjpaxton** [comment]
> Do you use Gnome or KDE Plasma? What is your version of xdg-desktop-portal-gtk (if you use Gnome) or xdg-desktop-portal-kde (if you use KDE Plasma)? And your version of xdg-desktop-portal?

I don't use a desktop environment, just a little window manager known as CalmWM (cwm).
The `xdg-desktop-portal` command does not exist on my system.

**Comment by grulja** [comment]
Then you need to install xdg-desktop-portal and xdg-desktop-portal-gtk, otherwise you will not be able to send files in Telegram. This is most likely also a bug in our Qt implementation, which causes your telegram to freeze, but still if I fix it, you will not be able to use it properly until you install mentioned portal support.

**Comment by mrjpaxton** [comment]
Hm, interesting. Well, I'll have those installed just in case!

I guess I should mention I have also had **more** FlatPak packages freeze when trying to open a file chooser in it, so this really is not Telegram's fault. It's gotta be some upstream library or problem.
