### ISSUE TITLE
wrong theme after using XFCE / GNOME

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/org.telegram.desktop#82]
I have Fedora Silverblue with GNOME and XFCE (along with rpm-ostree ..) not sure if this conflicts with the telegram theme ..

on GNOME (adwaita)
![2019-08-08_17-54](https://user-images.githubusercontent.com/17401812/62737219-a3f73200-ba05-11e9-95fd-a6ede20494e8.png)

flatpak list
https://paste.fedoraproject.org/paste/lX1kaQmayOckJjqatu1tgw/deactivate/OgEOgngKXR6nu6G6vQQs6Tu9rWWPWvTRyHova55D1qHZ3Fnz4mhbLKx6gEeZtX6f

**Comment by FastOSlinux** [comment]
with fresh install too 
![Captura de tela de 2019-08-08 19-24-49](https://user-images.githubusercontent.com/17401812/62741696-42899000-ba12-11e9-823c-8a3679fc586a.png)

**Comment by grulja** [comment]
What do you mean it's wrong? The window decorations or theme of the app itself?

**Comment by grulja** [comment]
Fixed with https://github.com/flathub/org.telegram.desktop/commit/be6087d536c42048f9e1ad45979b8323dc7023a1 for now.
