### ISSUE TITLE
[Show in folder | Open with | Save file as] Don't work!

### ISSUE THREAD

**Issue by retyui** [flathub/org.telegram.desktop#84]
### What happened:

1) Install telegram
2) Have a file sent to you that needs to be downloaded (eg video, document, non-compressed image)
3) Use "Open with" or right-click there is an option "Show in folder or Save file as" and select it
4) Notice nothing happens

### What I expected to happen:

Should work correctly (step 4)

### Version Info:

- Telegram Desktop 1.7.14
- Flatpak 1.4.2
- OS: Linux Mint 19.1 Cinnamon
- uname: `Linux am 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by grulja** [comment]
Should be fixed with the upcoming update to 1.8.1.
