### ISSUE TITLE
Displaying URLs is broken

### ISSUE THREAD

**Issue by bertogg** [flathub/org.telegram.desktop#92]
I'm using Telegram 1.8.8 (commit 078e3bd4760b) and every time I share a URL in a chat room it gets displayed like this:

![pic](https://user-images.githubusercontent.com/133365/65045737-01b55d00-d968-11e9-8f1b-cb80af7ba2cf.png)

**Comment by FastOSlinux** [comment]
same here, after update kde runtime

**Comment by bertogg** [comment]
Oh, that's right, the problem is in the kde runtime, if I revert the update then it works again.

So, `org.kde.Platform/x86_64/5.12`:

   - Commit `99d0d003f979f69c4b1db6f588c2457808a58412e707498dfd889d0683858c1e` works
   - Commit `5539ccd35690b5774e46e8d34fb576b0f86331c59cb8ee7a4ea31b38ccde5886` fails.

**Comment by gasinvein** [comment]
Just guessing: KDE/flatpak-kde-runtime@f4373394b5b6120ea5609802864e5bd3ca7e1e0c broke some private Qt API that Telegram uses.
Also Telegram doesn't build with latest KDE SDK:
```
In file included from /run/build/telegram-desktop/out/Release/Telegram_pch/stdafx.h:134:
/run/build/telegram-desktop/out/Release/../../Telegram/SourceFiles/ui/text/text.h:14:10: fatal error: private/qfontengine_p.h: No such file or directory
 #include <private/qfontengine_p.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by grulja** [comment]
Let's see if a rebuild against Qt 5.12.5 helps.

**Comment by gasinvein** [comment]
Seems like 4a7007f fixed this.

**Comment by bertogg** [comment]
I just updated the KDE runtime and Telegram and I confirm that it works fine now, thanks !

**Comment by bertogg** [comment]
I just updated the KDE runtime and this seems broken again.

**Comment by gasinvein** [comment]
Did KDE/flatpak-kde-runtime@3fb306e6e0487a2a93dcb94e6123e3a06c57a50b do this?

**Comment by Erick555** [comment]
It seems that telegram [has to be rebuild evrery time when qt is updated on runtime](https://github.com/telegramdesktop/tdesktop/issues/6584#issuecomment-533873143).
