### ISSUE TITLE
No native notifications option in Chrome/Chromium OS

### ISSUE THREAD

**Issue by flaksp** [flathub/org.telegram.desktop#93]
Chrome OS officially supports sending notifications from Linux. For example, `libnotify-bin` works correctly (for example `notify-send test`). But for some reason Telegram Desktop hides option to enable native notifications.

![image](https://user-images.githubusercontent.com/12474739/65071941-a9b92f00-d944-11e9-99d6-f7bdf6fd293f.png)

May be related to #1 and #55.

**Comment by gasinvein** [comment]
Notifications system was revoked upstream, can you please check if the issue still present?

**Comment by ilya-fedin** [comment]
Closing inactive issues
